openshift-psap/ci-artifacts

- build/Dockerfile
- build/root/usr/local/bin/run
- group_vars/all.yml
- playbooks/nvidia-gpu-operator-ci.yml
- roles/openshift_node/tasks/create_machine.yml
- roles/openshift_node/tasks/scaleup_checks.yml
This patch fixes the playbook `nvidia-gpu-operator-ci` to be run in containerized environments and ease the way the container can be called from CI environments
> Nightly builds

- build/Dockerfile
- build/root/usr/local/bin/run
- build/root/usr/local/bin/user_setup
This Patch:
- elevates verbosity from `v` to `vvv`
- enables a user at runtime so Ansible doesn't errors `KeyError: 'getpwuid(): uid not found:`
> Enable Ansible to run on OpenShift Ci environment 

- build/root/usr/local/bin/run
This PR removes a buggy workaround on the CI code that prevents the `master` branch from properly testing the GPU operator
see https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1338997427285266432/artifacts/gpu-operator-e2e/nightly/container-logs/test.log
```
===> Running GPU CI Test suite<===
Kubeconfiug found at /tmp/tmp.BU55psNfBG, proceeding with tests
uid=1011810000 gid=0(root) groups=0(root),1011810000
```
Signed-off-by: Kevin Pouget <kpouget@redhat.com>
> build/root/usr/local/bin/run: remove USER workaround that cannot work

- build/root/usr/local/bin/entrypoint
Trying to fix [this issue](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1348419454828023808) in the CI:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 147, in run
res = self._execute()
File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 620, in _execute
self._connection = self._get_connection(cvars, templar)
File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 909, in _get_connection
ansible_playbook_pid=to_text(os.getppid())
File "/usr/local/lib/python3.6/site-packages/ansible/plugins/loader.py", line 573, in get
obj = obj(*args, **kwargs)
File …
```
> build/root/usr/local/bin/entrypoint: make sure that USER is always set

- group_vars/all.yml
- roles/openshift_node/files/aws_machineset_json.sh
- roles/openshift_node/tasks/create_machine.yml
- roles/openshift_node/tasks/scaleup_checks.yml
The code was previously spinning up 2 replicas of GPU machines,
because the source machineset (the default worker one) had 2 replicas
by default.
The task in charge of checking the GPU node deployment was failing
because it was seeing 2x 'Running' while expecting only one.
Also fix 'deff' typo and remove trailing while spaces.
> roles/openshift_node: fix issue with GPU node scale-up

- roles/nv_gpu/tasks/install.yml
This should solve this error on the CI:
```
fatal: [localhost]: FAILED! => {
"attempts": 5,
"cmd": [
"oc",
"apply",
"-f",
"roles/nv_gpu/files/042_customresources.yaml"
],
"msg": "non-zero return code",
"stderr": "error: unable to recognize \"roles/nv_gpu/files/042_customresources.yaml\": no matches for kind \"ClusterPolicy\" in version \"nvidia.com/v1\"",
}
TASK [nv_gpu : Failed when creating the clusterpolicy CR for the GPU Operator] ***
```
> roles/nv_gpu/tasks/install.yml: give more delay for the GPU Operator CRD to be applied

- build/root/usr/local/bin/run
- group_vars/all.yml
- playbooks/nvidia-gpu-operator-commit-ci.yml
- roles/nv_gpu/tasks/ci_checks.yml
- roles/nv_gpu/tasks/install_nfd.yml
- roles/nv_gpu/tasks/install_nv.yml
- roles/nv_gpu/tasks/main.yml
- roles/nv_gpu_install_from_commit/files/helm_deploy_operator.sh
- roles/nv_gpu_install_from_commit/files/operator_ci_utils.yaml
- roles/nv_gpu_install_from_commit/files/operator_ci_utils_namespace.yml
- roles/nv_gpu_install_from_commit/files/operator_helper_image_builder.yaml
- roles/nv_gpu_install_from_commit/files/operator_image_builder_pod.yaml
- roles/nv_gpu_install_from_commit/files/operator_image_builder_script.yaml
- roles/nv_gpu_install_from_commit/files/operator_imagestream.yaml
- roles/nv_gpu_install_from_commit/files/operator_namespace.yaml
- roles/nv_gpu_install_from_commit/files/tuned_module_fuse.yaml
- roles/nv_gpu_install_from_commit/meta/main.yml
- roles/nv_gpu_install_from_commit/tasks/build.yml
- roles/nv_gpu_install_from_commit/tasks/cleanup.yml
- roles/nv_gpu_install_from_commit/tasks/deploy.yml
- roles/nv_gpu_install_from_commit/tasks/main.yml
- roles/nv_gpu_install_from_commit/tasks/undeploy.yml
- roles/nv_gpu_install_from_commit/vars/main.yml
- roles/openshift_node/tasks/main.yml
This PR adds the ability to run non-regression testing on a particular GPU-operator commit.
This allows testing the PR by running this command:
```./build/root/usr/local/bin/run gpu-commit-ci https://gitlab.com/kpouget_psap/gpu-operator.git devel```
with a pre-configured cluster:
```
PLAY RECAP *************************************************************************************************
localhost                  : ok=31   changed=28   unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
Thursday 17 December 2020  15:59:59 +0100 (0:00:38.643)       0:10:29.618 *****
===============================================================================
nv_gpu_install_from_commit : wait for the operator image to be built ------------------------------ 339.05s …
```
> gpu-operator: run CI checks against a given git commit

- group_vars/all.yml
- roles/nv_gpu/files/032_operator_sub.yml
- roles/nv_gpu/files/042_customresources.yml
- roles/nv_gpu/tasks/install_nfd.yml
- roles/nv_gpu/tasks/install_nv.yml
- roles/nv_gpu/tasks/main.yml
- roles/nv_gpu/tasks/uninstall_nv.yml
- roles/nv_gpu/tasks/verbose_failure.yml
- toolbox/deploy_nfd_from_operatorhub.sh
- toolbox/gpu-operator/deploy_from_commit.sh
- toolbox/gpu-operator/deploy_from_operatorhub.sh
- toolbox/gpu-operator/run_ci_checks.yml
- toolbox/gpu-operator/undeploy_from_commit.sh
- toolbox/gpu-operator/undeploy_from_operatorhub.sh
- toolbox/scaleup_gpu_node.sh
* 7ee0d4f - roles/nv_gpu/tasks/ci_checks.yml: capture the GPU-Operator image
* 77c645e - roles/nv_gpu: update GPU Operator OperatorHub deployment to v1.5.1
* 04878c6 - toolbox: use '#! /bin/bash -e' to catch errors before source '_common.sh'
* b83ca4d - toolbox/gpu-operator/deploy_from_operatorhub.sh: fix path to _common.sh
* ab1ab03 - toolbox: gpu-operator/undeploy_from_operatorhub.sh: new script
* fb4b504 - roles/nv_gpu/tasks/uninstall_nv.yml: new task book to undeploy after an OperatorHub deployment
* eef781f - group_vars/all.yml: undeploy_gpu_operator: default to 'no'
* 5239cd3 - roles/nv_gpu/tasks/verbose_failure.yml: make the file easier to read
* 526d64e - roles/nv_gpu/tasks/install_nfd.yml: remove unnecessary block/rescue
* 93bd254 - roles/nv_gpu/tasks/install_nv.yml: remove …
> Improve GPU-operator CI, switch to v1.5.1 and extend the toolbox

- build/root/usr/local/bin/run
- group_vars/all.yml
- roles/nv_gpu/tasks/ci_checks.yml
- roles/nv_gpu/tasks/verbose_failure.yml
- efae8c0 removes the `ignore_errors` flag on the GFD flag, now that `master` and `1.5.2` are passing it successfully
- cfa402a removes extra debugging output logs from the main logs, and moves them to `/tmp/artifacts/`, and hopefully these files will be made available in the `artifacts` linked with the test execution
> Improve CI: store extra logs to artifacts directory

- install_dir/.openshift_install.log
- roles/nv_gpu_install_from_commit/files/operator_helper_image_builder.yml
- roles/nv_gpu_install_from_commit/tasks/build.yml
We are currently using a Dockerfile from a blog post from 2019, this
Dockerfile is the latest upstream version at
https://github.com/containers/buildah/blob/master/contrib/buildahimage/upstream/Dockerfile
maintained by the buildah dev team
> Use container dev team Buildah Dockerfile

- build/root/usr/local/bin/run
- playbooks/build-psap-ci.yml
- playbooks/deploy-gpu-operator-from-commit.yml
- playbooks/deploy-gpu-operator-from-operatorhub.yml
- playbooks/gpu-burst.yml
- playbooks/nvidia-gpu-operator-ci.yml
- playbooks/nvidia-gpu-operator-commit-ci.yml
- playbooks/openshift-odh-ci.yml
- playbooks/openshift-psap-ci.yml
- playbooks/scaleup-gpu-node.yml
- roles/build_ci_image/files/execution_pod.yml
- roles/build_ci_image/files/helm_deploy_operator.sh
- roles/build_ci_image/files/image_builder.yml
- roles/build_ci_image/files/imagestream.yml
- roles/build_ci_image/files/namespace.yml
- roles/build_ci_image/files/operator_ci_utils.yml
- roles/build_ci_image/files/operator_ci_utils_namespace.yml
- roles/build_ci_image/files/operator_helper_image_builder.yml
- roles/build_ci_image/files/operator_image_builder_script.yml
- roles/build_ci_image/files/tuned_module_fuse.yml
- roles/build_ci_image/meta/main.yml
- roles/build_ci_image/tasks/build.yml
- roles/build_ci_image/tasks/cleanup.yml
- roles/build_ci_image/tasks/main.yml
- roles/build_ci_image/vars/main.yml
- roles/check_deps/tasks/main.yml
- roles/openshift_node/tasks/scaleup_checks.yml
- toolbox/local-ci/cleanup.sh
- toolbox/local-ci/deploy.sh
This PR allows running a given commit of the `ci-artifact` repository on a local OpenShift cluster:
Example:
```
./build/root/usr/local/bin/run ci-builder https://github.com/openshift-psap/ci-artifacts.git master
```
I mark this PR as draft because the command to run on the CI pod is currently hardcoded in `roles/build_ci_image/files/execution_pod.yaml`:
```
spec:
containers:
- name: ci-artifacts
command:
- /bin/sh
- -c
- bash -x run gpu-commit-ci https://gitlab.com/kpouget_psap/gpu-operator devel
```
I would like to be able to pass `run gpu-commit-ci https://gitlab.com/kpouget_psap/gpu-operator devel` in the `run` command-line above, as `ANSIBLE_OPTS` or directly on the command-line.
> Run CI on local cluster

- .github/workflows/sync-release-branches.yml
Protected branch don't like it ...
> .github/workflows/sync-release-branches.yml: don't use the force to push

- group_vars/all.yml
- roles/check_deps/tasks/main.yml
- toolbox/_common.sh
`roles/check_deps/tasks/main.yml` is executed at the beginning of every playbook / toolbox script.
This patch simplifies what is checked and automates the computation of `openshift_release`
> roles/check_deps/tasks/main.yml: simplify check_deps and compute openshift_release if not set

- roles/nv_gpu/tasks/install_nv.yml
- roles/nv_gpu_install_from_commit/files/helm_deploy_operator.sh
* 9168c2d - roles/nv_gpu/tasks/install_nv.yml: Ensure that the GPU Operator PackageManifest exists
Without this patch, the following commands may erroneously succeed
(if not ignored), because of the `| jq`...
Example:
TASK: nv_gpu : Get the version of the GPU Operator on OperatorHub
changed: True
<command> oc get packagemanifests/gpu-operator-certified -n openshift-marketplace -ojson | jq -r .status.channels[0].currentCSV
<stderr> Error from server (NotFound): packagemanifests.packages.operators.coreos.com "gpu-operator-certified" not found
---
* 541c5da - roles/nv_gpu_install_from_commit/files/helm_deploy_operator.sh: fix image name transformation
The default `version` of the `devicePlugin` image changed a few days
ago [1] to use the `-ubi8` image by default. This broke the automated …
> Small fixes

- build/root/usr/local/bin/run
- playbooks/entitlement.yml
- roles/entitlement/files/apply_template.py
- roles/entitlement/files/mc_pem.yml
- roles/entitlement/files/mc_rhsm.yml
- roles/entitlement/files/rhsm.conf
- roles/entitlement/files/test_pod.yml
- roles/entitlement/tasks/deploy.yml
- roles/entitlement/tasks/inspect.yml
- roles/entitlement/tasks/main.yml
- roles/entitlement/tasks/test_wait.yml
- roles/entitlement/tasks/undeploy.yml
- roles/entitlement/vars/main.yml
- toolbox/entitlement/deploy.sh
- toolbox/entitlement/inspect.sh
- toolbox/entitlement/test.sh
- toolbox/entitlement/undeploy.sh
- toolbox/entitlement/wait.sh
```
toolbox/entitlement/deploy.sh
```
deploys either from a pre-prepared YAML resource file (CI) or from a PEM key
```
toolbox/entitlement/undeploy.sh
```
deletes our MachineConfig objects
```
toolbox/entitlement/test.sh
```
tests if `dnf info kernel-core` completes successfully
```
toolbox/entitlement/wait.sh
```
tests if `dnf info kernel-core` completes successfully within `10*30` seconds
```
toolbox/entitlement/inspect.sh
```
tests if `dnf info kernel-core` completes successfully and gathers extra information about the MachineConfig(Pools), to help debugging entitlement problems
> toolbox: entitlement: new set of tools

- build/root/usr/local/bin/run
- roles/entitlement/files/test_pod.yml
- roles/entitlement/tasks/test_wait.yml
The CI failed last night because the entitlement test did not succeed (nor properly fail):
```
/opt/ci-artifacts/src/playbooks/roles/entitlement/tasks/test_wait.yml:18
Tuesday 02 March 2021  23:35:40 +0000 (0:00:00.023)       0:00:01.262 ********* 
{"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2021-03-03T01:35:38Z"}
{"component":"entrypoint","file":"prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2021-03-03T01:35:53Z"}
```
This PR fixes the issue.
> Fix entitlement failure

- build/root/usr/local/bin/run
- roles/nv_gpu/files/gpu/020_operator_sub.yml
- roles/nv_gpu/tasks/install_nv.yml
- roles/nv_gpu/tasks/uninstall_nv.yml
- roles/nv_gpu/vars/main.yml
- toolbox/gpu-operator/deploy_from_operatorhub.sh
This PR allows installing an older version of the GPU Operator from OperatorHub, but requested a specific ClusterServiceVersion and marking the as Manual.
By default, no `gpu_operator_operatorhub_version` is empty, so the last release available on OperatorHub is installed.
The toolbox is extended to receive an optional version identifier as argument
```
toolbox/gpu-operator/deploy_from_operatorhub.sh [<version to install>]
```
The CI `run` command is extended to receive an optional version identifier as argument:
```
build/root/usr/local/bin/run gpu-ci [version]
build/root/usr/local/bin/run gpu-helm-ci <version>
```
A follow-up PR on OpenShift-release will integrate the testing of older versions in the CI
> roles/nv_gpu: allow installing an older version

- roles/entitlement/tasks/test_wait.yml
- roles/entitlement/vars/main.yml
- roles/nv_gpu/tasks/install_nv.yml
* 2a91812 - roles/nv_gpu/tasks/install_nv.yml: extend the # of retries for the InstallPlan to show up
---
* 2a89a88 - roles/entitlement: retry 20 times when waiting
---
* b0bf982 - roles/entitlement/tasks/test_wait.yml: stop waiting for Pod completion after 120s
---
> Extend (and fix) waiting times

- build/root/usr/local/bin/run
- roles/nv_gpu/tasks/main.yml
- roles/nv_gpu/tasks/test_nfd_gpu.yml
- roles/nv_gpu/vars/main.yml
- toolbox/nfd/has_gpu_nodes.sh
- toolbox/nfd/wait_gpu_nodes.sh
This PR improves the detection of GPU nodes in the cluster:
instead of relying on AWS Machines and types to detect the presence of GPU nodes, use NFD to ...
1. test if a GPU node is available (see NVIDIA GPU labels [there](https://github.com/NVIDIA/gpu-operator/blob/master/pkg/controller/clusterpolicy/state_manager.go#L26))
2. if not available, scale-up the cluster with AWS MachineSet
3. wait for the GPU node to show up
this PR implements steps 1 and 3.
Incidentally, the PR also removes the strong dependency on AWS infrastructure, which is now only required when no GPU node is available at the beginning of the execution.
> Add ability to test and wait for NFD-labelled GPU nodes

- README.md
- build/root/usr/local/bin/run
- callback_plugins/human_log.py
- playbooks/gpu-burst.yml
- roles/entitlement/tasks/inspect.yml
- roles/entitlement/tasks/main.yml
- roles/entitlement/tasks/test_wait.yml
- roles/entitlement/vars/main.yml
- roles/nv_gpu/tasks/ci_checks.yml
- roles/nv_gpu/vars/main.yml
- roles/nv_gpu_install_from_commit/tasks/deploy.yml
- toolbox/entitlement/test.sh
* 10d6e0c - roles/entitlement/tasks/inspect.yml: Get the state of the nodes: correctly call 'oc get nodes'
---
* a73721f - callback_plugins/human_log.py: correctly group 'task.get_path()' with its task logs
---
* ae0128e - roles/entitlement/tasks/test_wait.yml: retry '0' times when not waiting
---
* 0e1c453 - toolbox/entitlement/test.sh: add '--no-inspect' flag
This flag allows muting the inspection tasks (eg, when we expect the
test to confirm that the entitlement is not deployed)
---
* dc2d530 - roles/nv_gpu/tasks/ci_checks.yml: check that NFD is live and GPU nodes are available
---
* 5fd73f8 - callback_plugins/human_log.py: improve readability
The task output now looks like this:
```
---
---
roles/nv_gpu/tasks/ci_checks.yml:4
TASK: nv_gpu : CRD check - Ci mode
<command> oc get …
```
> Fix various bugs

- roles/nv_gpu/tasks/install_nv.yml
The old way (using `-loperators.coreos.com/gpu-operator-certified.openshift-operators`)
wasn't supported in OCP 4.5, causing the retry loop to fail.
> roles/nv_gpu/tasks/install_nv.yml: rewrite 'Find the GPU Operator OperatorHub InstallPlan'

- roles/nv_gpu/tasks/install_nv.yml
Example of what we can find in the catalog operator logs:
> 1 queueinformer_operator.go:290] sync "openshift-operators" failed: constraints not satisfiable: no operators found matching the 
subscription criteria for gpu-operator-certified, a subscription to package gpu-operator-certified exists in the namespace
> 1 event.go:282] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"", Name:"openshift-operators", UID:"f03ec97c-fdd7-4815-9bb8-ef14f588042d", APIVersion:"v1", ResourceVersion:"57004", FieldPath:""}): type: 'Warning' reason: 'ResolutionFailed' constraints not satisfiable: no operators found matching the subscription criteria for gpu-operator-certified, a subscription to package gpu-operator-certified exists in the namespace
```
> roles/nv_gpu/tasks/install_nv.yml: get debug logs when InstallPlan lookup fails

- README.md
- build/root/usr/local/bin/run
- callback_plugins/human_log.py
- playbooks/gpu-burn.yml
- roles/gpu_burn/files/gpu_burn_cm_entrypoint.yml
- roles/gpu_burn/files/gpu_burn_pod.yml
- roles/gpu_burn/tasks/main.yml
- roles/gpu_burn/vars/main.yml
- toolbox/gpu-operator/run_gpu_burn.sh
* 4dd82ec - callback_plugins/human_log.py: correctly group 'task.get_path()' with its task logs
---
* 16dd890 - callback_plugins/human_log.py: improve readability
The task output now looks like this:
```
---
---
roles/nv_gpu/tasks/ci_checks.yml:4
TASK: nv_gpu : CRD check - Ci mode
<command> oc get crds/clusterpolicies.nvidia.com
<stdout> NAME                         CREATED AT
<stdout> clusterpolicies.nvidia.com   2021-03-08T09:27:30Z
Monday 08 March 2021  10:48:52 +0100 (0:00:01.961)       0:00:04.545 **********
```
or when it fails:
```
---
---
roles/nv_gpu/tasks/ci_checks.yml:15
TASK: nv_gpu : Ensure that NFD found nodes with GPU labels
----- FAILED ----
msg: non-zero return code
<command> (   oc get nodes -oname --ignore-not-found=false -l feature.node.kubernetes.io/pci-10de.present …
```
> toolbox: add toolbox/gpu-operator/run_gpu_burn.sh script

- build/root/usr/local/bin/run
- toolbox/_common.sh
Prepare artifact directory in `toolbox/_common.sh`, and create one directory (with a hour/minute timestamp) per toolbox operation, so that we can better understand what logs belong to which toolbox task.
> Prepare artifact directory in toolbox/_common.sh

- .github/workflows/sync-release-branches.yml
- build/root/usr/local/bin/run
* f0c7622 - .github/workflows/sync-release-branches.yml: do not sync release-4.4 and release-next
---
* d436cba - build/root/usr/local/bin/run: allow passing a custom repo/branch to 'gpu-commit-ci'
> Do not sync release-4.4 and release-next and do not sync release-4.4 and release-next

- build/root/usr/local/bin/run
- roles/gpu_operator_wait_deployment/tasks/main.yml
- toolbox/_common.sh
- toolbox/cluster/capture_environment.sh
- toolbox/gpu-operator/diagnose.sh
* d627317 - gpu_operator_wait_deployment: fix to properly wait for 1.4.0 deployment
Test of 1.4.0 was failing because multiple Pod showed up, while we
expected only one:
```
<command> oc get pods --field-selector=status.phase=Succeeded -n gpu-operator-resources -oname --no-headers
==> FAILED attempt #15/15
<stdout> pod/nvidia-device-plugin-validation
<stdout> pod/nvidia-driver-validation
```
---
* e2417ba - toolbox: change ansible log file to '_ansible.log'
---
* d67c7ea - toolbox: move capture_environment.sh to cluster/capture_environment.sh
---
* ccd9cec - build/root/usr/local/bin/run: remove old flags
> Fix 1.4.0 and small refactoring steps

- .github/workflows/sync-release-branches.yml
- roles/capture_environment/tasks/main.yml
- roles/cluster_scaleup/tasks/main.yml
- roles/cluster_scaleup/tasks/scaleup.yml
- roles/entitlement_test_wait/tasks/main.yml
- roles/gpu_operator_deploy_custom_commit/tasks/build.yml
- roles/gpu_operator_deploy_custom_commit/tasks/deploy.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/main.yml
- roles/gpu_operator_wait_deployment/tasks/main.yml
- roles/local-ci_deploy/tasks/main.yml
- roles/nfd_deploy/tasks/main.yml
- roles/nfd_has_labels/tasks/main.yml
- roles/nfd_test_wait_gpu/tasks/main.yml
- toolbox/_common.sh
* b363aab - refactoring: use one-line fail/debug tasks
---
* 91c95aa - capture_environment: remove unused variable
---
* 1d2ad96 - nfd_has_labels: do not use 'ignore_errors' in rescue check
---
* cc1d2d6 - .github/workflows/sync-release-branches.yml: do sync 4.5
---
* 3b1d744 - gpu_operator_wait_deployment: fix 1.4.0 testing
---
* 94c6e2d - gpu_operator_deploy_custom_commit: add debug commands to better understand 'ImagePullBackOff' errors
---
* d3f68bb - toolbox: move ansible_facts to $ARTIFACT_DIR
---
> Various refactoring and fixes

- build/root/usr/local/bin/run
- playbooks/cluster_upgrade_to_image.yml
- roles/cluster_upgrade_to_image/defaults/main/config.yml
- roles/cluster_upgrade_to_image/meta/main.yml
- roles/cluster_upgrade_to_image/tasks/main.yml
- toolbox/cluster/upgrade_to_image.sh
This PR adds a new role for triggering an upgrade of OpenShift to a given image.
At the moment, no check is performed against the target image, and the upgrade is forced.
An upgrade hook is added to the CI entrypoint: `run cluster-upgrade`, which expects to receive the target image with `CLUSTER_UPGRADE_TARGET_IMAGE` environment variable.
The CI configuration is being updated with this PR https://github.com/openshift/release/pull/17498
It will remain as a presubmit hook until the GPU Operator supports cluster upgrade without uninstalling the operator.
> cluster_upgrade_to_image: new role

- callback_plugins/json_to_logfile.py
- config/ansible.cfg
- toolbox/_common.sh
The purpose of this PR is to have another logfile using the JSON format, so that we can easily parse and display the result of the test steps in a website, by fetching the JSON logfile and plotting the relevant information in HTML.
> Store ansible output as a json logfile

- roles/gpu_operator_deploy_from_operatorhub/tasks/main.yml
This error happens every once in a while:
```
<command> oc get packagemanifests/gpu-operator-certified -n openshift-marketplace
<stderr> Error from server (NotFound): packagemanifests.packages.operators.coreos.com "gpu-operator-certified" not found
```
I would like to see if the `CatalogSource/certified-operators` is not ready when it happens.
> gpu_operator_deploy_from_operatorhub: Capture the state of the CatalogSource/certified-operators

- README.md
- roles/nfd_deploy/defaults/main/config.yml
- roles/nfd_deploy/files/040_customresources.yml
- roles/nfd_deploy/tasks/main.yml
- roles/nfd_deploy/vars/main/resources.yml
- roles/nfd_undeploy/tasks/main.yml
- toolbox/nfd/deploy_from_operatorhub.sh
This PR enables the deployment of the NFD operator from any channel (or the channel matching the current OCP version).
> nfd_deploy: use NFD version == OCP version (except for 4.8)

- build/root/usr/local/bin/run
This test does not deploy the GPU Operator, but only validates that it is running properly.
It will be used to validate that the operator is still functional after OpenShift cluster upgrade.
> build/root/usr/local/bin/run: add gpu-operator_validate-deployment test

- build/Dockerfile
- build/root/usr/local/bin/run
- roles/gpu_operator_deploy_from_operatorhub/tasks/main.yml
- toolbox/gpu-operator/diagnose.sh
- toolbox/gpu-operator/must-gather.sh
This PR creats a `must-gather` plugin image for the GPU Operator.
The first patch is focused on collecting all the relevant information.
The second patch is the `must-gather` entrypoint (see [here](https://github.com/openshift/enhancements/blob/master/enhancements/oc/must-gather.md) and [there](https://github.com/openshift/must-gather)) and image recipe.
> toolbox: new script gpu-operator/must-gather.sh

- roles/entitlement_deploy/files/mc_pem.yml
- roles/entitlement_deploy/files/mc_rhsm.yml
Testing is failing on OCP 4.5 and 4.6 since we switched to `--pem` key deployment (instead of deployment predefined MC resources from the secrets)
> entitlement_deploy: use ignition v3.0.0 for compatibility with OCP 4.5 and 4.6

- build/Dockerfile
Otherwise it complains with
```
[must-gather-r5z75] OUT downloading gather output
WARNING: cannot use rsync: rsync not available in container
```
> build/Dockerfile: install rsync for oc adm must-gather

- roles/nfd_deploy/tasks/main.yml
This doesn't work:
```
roles/nfd_deploy/tasks/main.yml:53
TASK: nfd_deploy : Wait for the NFD Operator OperatorHub ClusterServiceVersion
<command> oc get ClusterServiceVersion -l operators.coreos.com/nfd.openshift-nfd -oname -n openshift-nfd
```
while this debug task worked right after:
```
roles/nfd_deploy/tasks/main.yml:64
TASK: nfd_deploy : List the ClusterServiceVersion in the openshift-nfd namespace
<command> oc get ClusterServiceVersion -n openshift-nfd
<stdout> NAME                        DISPLAY                  VERSION   REPLACES   PHASE
<stdout> nfd.4.5.0-202104130540.p0   Node Feature Discovery   4.5.0                Succeeded
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.5-gpu-operator-e2e-140/1 …
> nfd_deploy: add hook for OCP 4.5 for finding the CSV

- build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh
- build/root/usr/local/bin/entitle.sh
- playbooks/gpu_operator_set_repo-config.yml
- roles/entitlement_deploy/defaults/main/config.yml
- roles/entitlement_deploy/files/mc_rhsm_ca.yml
- roles/entitlement_deploy/tasks/main.yml
- roles/entitlement_deploy/vars/main/resources.yml
- roles/entitlement_test_wait/files/entitlement-tester_entrypoint.yml
- roles/gpu_operator_set_repo-config/defaults/main/config.yml
- roles/gpu_operator_set_repo-config/meta/main.yml
- roles/gpu_operator_set_repo-config/tasks/main.yml
- toolbox/entitlement/deploy.sh
- toolbox/gpu-operator/set_repo-config.sh
This PR add a new toolbox command `toolbox/gpu-operator/set_repo-config.sh <repofile|--rhel-beta>` to tell the GPU Operator driver Pod to use a custom DNF repo list or RHEL beta repositories.
It should solve OCP 4.8 testing, at least when the self-signed certificate is removed from the chain, or we change the repo URL
> gpu_operator_set_repo-config: new role to set spec.driver.repoConfig

- roles/gpu_operator_wait_deployment/tasks/main.yml
I noticed that Prometheus test is failing but currently ignored (`ignore_errors: true`)
```
2021-05-05 23:58:16,931 p=3874 u=psap-ci-runner n=ansible | TASK: gpu_operator_wait_deployment : Wait for Prometheus to pick up the DCGM endpoint
2021-05-05 23:58:16,932 p=3874 u=psap-ci-runner n=ansible | msg: non-zero return code
2021-05-05 23:58:16,932 p=3874 u=psap-ci-runner n=ansible | 
2021-05-05 23:58:16,932 p=3874 u=psap-ci-runner n=ansible | <command> oc get secret prometheus-k8s -n openshift-monitoring -ojson | jq -r '.data["prometheus.yaml.gz"]' | base64 -d | gunzip | grep dcgm
2021-05-05 23:58:16,932 p=3874 u=psap-ci-runner n=ansible | 
2021-05-05 23:58:16,932 p=3874 u=psap-ci-runner n=ansible | 
2021-05-05 23:58:16,932 p=3874 u=psap-ci-runner n=ansible | ==> FAILED attempt #1/5 …
```
> gpu_operator_wait_deployment: wait longer for Prometheus to pick up the DCGM metrics

- build/Dockerfile
Helm was incorrectly downloaded at this path `/usr/local/bin/linux-amd64/helm`.
I'm not sure how to get `tar` to extract directly to the right directory ...
> build/Dockerfile: move helm to the right directory

- roles/entitlement_undeploy/tasks/main.yml
https://github.com/openshift-psap/ci-artifacts/pull/124/files added MachineConfig `50-rhsm-repo-ca` resource, but it wasn't included in `entitlement_undeploy` cleanup
---
Checklist (just to see how it behaves)
> entitlement_undeploy: also delete 50-rhsm-repo-ca

- roles/gpu_operator_run_gpu-burn/tasks/main.yml
This role failed in a recent [test](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/120/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-e2e/1390217302070267904/artifacts/gpu-operator-e2e/presubmit-operatorhub/artifacts/090951__gpu-operator__run_gpu_burn/_ansible.log) because the Pod was in `Pending` state at the end of the retry counter, 
but not enough information were captured to understand what happened.
```
2021-05-06 09:20:06,352 p=5502 u=psap-ci-runner n=ansible | roles/gpu_operator_run_gpu-burn/tasks/main.yml:46
2021-05-06 09:20:06,352 p=5502 u=psap-ci-runner n=ansible | TASK: gpu_operator_run_gpu-burn : Wait for GPU burn Pods to complete
2021-05-06 09:20:06,352 p=5502 u=psap-ci-runner n=ansible | ----- FAILED …
```
> gpu_operator_run_gpu-burn: improve and store pod description

- roles/gpu_operator_wait_deployment/tasks/main.yml
When [PR 217](https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/217) will be merged in the GPU Operator, the master branch testing will fail as they are changing the way the operator internally validates its deployment.
This PR allows the testing of the old Pod-based validation and new DS-based validation, by checking if the `ClusterPolicy` has the `.spec.validator.version` stanza or not.
I tested this PR locally and it works as expected when everything is correctly deployed,
and it's also part of https://github.com/openshift-psap/ci-artifacts/pull/151 where I'm working with NVIDIA to getting the PR to work properly on OpenShift.
--
This PR can be merged independently of NVIDIA's, as it must work properly before (testing of versions < 1.7.0) and after the merge (testing …
> gpu_operator_wait_deployment: update to support new (>= v1.7.0) GPU Operator validator

- roles/gpu_operator_set_repo-config/tasks/main.yml
I faced 3 issues to get RHEL 8.4 beta repo-list to work as expected in
the GPU Operator driver-container:
a) the driver-container script tries to disable some repo, so if the
file is readonly, it fails (https://gitlab.com/nvidia/container-images/driver/-/issues/25)
b) it needs packages not available in the beta mirror, so these extra
repo must be available, eg (from install of `kernel-devel`):
```
perl-Encode              x86_64  4:2.97-3.el8                            rhel-8-beta-baseos-rpms           1.5 M
perl-Digest-MD5          x86_64  2.55-396.el8                            rhel-8-for-x86_64-appstream-rpms   37 k
openssl                  x86_64  1:1.1.1g-15.el8_3                       rhel-8-for-x86_64-baseos-rpms     707 k
```
c) the default repo cannot be fetched AFAIU, so they …
> gpu_operator_set_repo-config: fix RHEL 8.4-beta repo-list

- CHANGELOG.rst
- docs/toolbox/gpu_operator.rst
- roles/gpu_operator_deploy_from_operatorhub/defaults/main/config.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml
- roles/gpu_operator_deploy_from_operatorhub/templates/020_operator_sub.yml.j2
- roles/gpu_operator_deploy_from_operatorhub/vars/main/resources.yml
- toolbox/gpu-operator/deploy_from_operatorhub.sh
Until `v1.6.2`, the GPU Operator was only using the `stable` channel, so this information was hard-coded in the `Subscription` resource. With `v1.7.0`, NVIDIA chose to use one channel per (major) release, so we need to allow it customization.
> gpu_operator_deploy_from_operatorhub: add support for setting the channel

- build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh
- build/root/usr/local/bin/ci_entrypoint_sro.sh
- config/ansible.cfg
- roles/gpu_operator_capture_deployment_state/tasks/main.yml
- toolbox/_common.sh
- toolbox/gpu-operator/diagnose.sh
* 7850818 - build/root/usr/local/bin/ci_entrypoint_*: trap only on EXIT
Otherwise, when trapping on ERR and EXIT, the trap gets executed twice
when an error occurs.
See the top of https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.8-gpu-operator-e2e-master/1395152369477488640/artifacts/gpu-operator-e2e-master/nightly/artifacts for an example.
---
* 18e0139 - toolbox/gpu-operator/diagnose.sh: run capture_deployment_state.sh and capture_environment.sh only once with --run-all
When test diagnose test was failing, `capture_deployment_state` was
running twice (once after the test failure, one at the end of the
diagnose.
See there for an example:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/ …
> Various improvements around the logging

- build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh
- toolbox/_common.sh
- toolbox/gpu-operator/must-gather.sh
* aadd2ed - toolbox: update _common.sh and gpu-operator/must-gather.sh to properly fetch `ARTIFACT_EXTRA_LOGS_DIR`  
* 76f0518 - build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh: correctly pass `OPERATOR_CHANNEL` to deploy script
> Fix various issues

- build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh
- toolbox/gpu-operator/must-gather.sh
* 13d2409 - ci_entrypoint_gpu-operator.sh: get ARTIFACT_EXTRA_LOGS_DIR value from toolbox/_common.sh
* 4b271a6 - toolbox/gpu-operator/must-gather.sh: fix when called directly
> Properly call gpu-operator/must-gather.sh and store its logs

- .github/workflows/check_consistency.yml
- CHANGELOG.rst
- README.rst
- docs/index.rst
- docs/toolbox/repo.rst
- roles/entitlement_test_in_cluster/defaults/main/config.yml
- roles/gpu_operator_deploy_from_operatorhub/vars/main/resources.yml
- roles/nfd_operator_deploy_custom_commit/vars/main/resources.yml
- roles/sro_deploy_custom_commit/vars/main/resources.yml
- roles/sro_undeploy_custom_commit/vars/main/resources.yml
- toolbox/repo/validate_role_files.py
- toolbox/repo/validate_role_vars_used.py
This PR creates a new `pull_request` GitHub Action to validate:
1. that all the variables defining a filepath (`roles/`) do point to an existing file
2. that all the variables defined are actually used in their role (with an exception for symlinks, shared between `undeploy` -> `deploy`).
This should prevent the problem solved by https://github.com/openshift-psap/ci-artifacts/pull/195 to happen again.
The PR also fixed problems found by the checks (only unused variables).
> Introduce a Github Action for checking ansible variable consistency

- subprojects/ci-mirror/mirrors/dataset/sync.sh
- subprojects/ci-mirror/openshift/template.yaml
- The SCC is cluster-scoped so the name should contain the mirror namespace to avoid clash
- URL contained // twice
> [ci-mirror] Some small mirror fixes

- build/root/usr/local/bin/run
- docs/ci/files.rst
- docs/ci/intro.rst
- docs/index.rst
- roles/check_deps/tasks/main.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml
- roles/nfd_operator_deploy_from_operatorhub/tasks/main.yml
- toolbox/_common.sh
* 83693b8 - CI: run: Remove old single-worded entrypoint definitions
---
* af9948c - CI: run: detect when cluster became unreachable during the testing
---
* 6c9b3d0 - toolbox: expose 'artifact_dir' as ansible variable
And ensure it is set in 'check_deps' role.
---
* 9a51d1a - gpu_operator_deploy_from_operatorhub: mark packagemanifests/gpu-operator-certified not found as flake
---
* 6d4b600 - nfd_operator_deploy_from_operatorhub: mark packagemanifests/nfd not found as flake
---
* dd01e42 - docs: introduce 'ci' section and document special files
---
> CI: detect flakes due to packagemanifest not found and cluster unreachable 

- CHANGELOG.rst
- CONTRIBUTING.rst
- roles/cluster_set_scale/tasks/main.yml
- roles/cluster_upgrade_to_image/tasks/main.yml
- roles/entitlement_inspect/tasks/main.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_clusterpolicy.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_bundle.yml
- roles/nfd_operator_deploy_from_operatorhub/tasks/main.yml
* 66cce04 - {nfd,gpu}_operator_deploy_from_operatorhub: sed/subscriptions/subscriptions.operators.coreos.com
`subscription` object name may be used by the KNative (in addition to
OLM):
```
$ oc get crd -A | grep subscriptions
subscriptions.messaging.knative.dev   2021-06-07T14:57:28Z
subscriptions.operators.coreos.com    2021-06-06T16:45:30Z
```
```
$ oc explain subscriptions
KIND:     Subscription
VERSION:  messaging.knative.dev/v1
```
This breaks commands expecting OLM subscription resources like
```
oc get subscription/nfd
```
---
* 737f0c5 - gpu_operator_deploy_from_operatorhub: wait for CRD instead of waiting for CR creating
---
* 413b3ea - Always store 'oc describe' into an {{ artifact_extra_logs_dir }} file
---
> {nfd,gpu}_operator_deploy_from_operatorhub: sed/subscriptions/subscriptions.operators.coreos.com + minor updates 

- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_clusterpolicy.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_bundle.yml
b510172de7d22ec83994d2b5dfc5286651205ccd - Fix clusterpolicy.nvidia.com -> clusterpolicies.nvidia.com typo that caused CI failures
25c1df404007437e37e1ce7f561cb093deab2412 - Fix broken waiting for CSV controller operator deployment image stanza update. It was racey so it wasn't noticed until now
a1c5c94d3d39bda4fad5245f85ffc7b432cccd98 - has_clusterpolicy_cr renamed to more precise has_clusterpolicy_crd
> Fix clusterpolicy.nvidia.com -> clusterpolicies.nvidia.com typo that caused CI failures

- toolbox/gpu-operator/deploy_from_operatorhub.sh
This fixes CI failures from lines like:
openshift/release@4a04e51/ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.6.yaml#L90
Which pass 2 parameters (version and channel) to said script
> fixes toolbox/gpu-operator/deploy_from_operatorhub.sh regression, it didnt accept more than one parameter

- CHANGELOG.rst
- CONTRIBUTING.rst
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_clusterpolicy.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_bundle.yml
- roles/nfd_deploy/tasks/main.yml
Backport of https://github.com/openshift-psap/ci-artifacts/pull/207 fix to `stable-v0.1` branch.
> Backport: {nfd,gpu}_operator_deploy_from_operatorhub: sed/subscriptions/subscriptions.operators.coreos.com

- roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml
- roles/gpu_operator_bundle_from_commit/files/operator_image_builder_script.yml
This change modifies the process of building a new GPU Operator image
from a particular commit to match the updated make process. This includes
support for specifying base images through make variables (docker build args)
and removes the need for executing sed commands on the docker files.
See https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/251
Signed-off-by: Evan Lezar <elezar@nvidia.com>
> Update gpu-operator image build for new Make target

- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml
- roles/gpu_operator_undeploy_from_operatorhub/tasks/main.yml
PR https://github.com/openshift-psap/ci-artifacts/pull/207 started to fix this, this patch just add two more lines to the fix
Append operators.coreos.com to tasks deploying GPU operator from catalog
> Append operators.coreos.com to tasks deploying GPU operator from catalog

- roles/entitlement_test_wait_deployment/files/entitlement-tester_entrypoint.yml
A follow-up task could be to do this check before deploying the key, and writing a warning into `$ARTIFACT_DIR/WARNING` if it is expiring soon. `ci-dashboard` could also display the content of this file ...
> entitlement_test_wait_deployment: check PEM expiration date and warn if it expires in less that 48h.

- roles/entitlement_deploy/files/apply_template.py
- roles/entitlement_deploy/files/mc_pem.yml
- roles/entitlement_deploy/files/mc_rhsm.yml
- roles/entitlement_deploy/files/mc_rhsm_ca.yml
- roles/entitlement_deploy/tasks/main.yml
- roles/entitlement_inspect/tasks/main.yml
On no-worker clusters, we want to target the masters with our machine
configs rather than the workers, because there are no workers.
We check that by looking at the Scheduler CR `.spec.mastersSchedulable`
stanza
> Support entitlement on no-workers clusters

- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml
- roles/nfd_operator_deploy_from_operatorhub/tasks/main.yml
Cluster Pools (cf this https://github.com/openshift/release/pull/20601) fail because of this error:
```
2021-07-27 09:18:54,314 p=2875 u=psap-ci-runner n=ansible | roles/nfd_operator_deploy_from_operatorhub/tasks/main.yml:10
2021-07-27 09:18:54,314 p=2875 u=psap-ci-runner n=ansible | TASK: nfd_operator_deploy_from_operatorhub : Ensure that the NFD Operator PackageManifest exists
2021-07-27 09:18:54,314 p=2875 u=psap-ci-runner n=ansible | msg: non-zero return code
2021-07-27 09:18:54,314 p=2875 u=psap-ci-runner n=ansible | 
2021-07-27 09:18:54,315 p=2875 u=psap-ci-runner n=ansible | <command> oc get packagemanifests/nfd -n openshift-marketplace
2021-07-27 09:18:54,315 p=2875 u=psap-ci-runner n=ansible | 
2021-07-27 09:18:54,315 p=2875 u=psap-ci-runner n=ansible | <stderr> error: the server …
```
> {nfd,gpu}_operator_deploy_from_operatorhub: better wait for packagemanifest to be available

- build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh
Without this fix, the code produces:
```
+ '[' 1.4.0 ']'
+ OPERATOR_VERSION='--version={1.4.0}'
+ shift
+ '[' stable ']'
+ OPERATOR_CHANNEL='--channel={stable}'
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.5-gpu-operator-e2e-140/1420157171710038016/artifacts/gpu-operator-e2e-140/nightly/build-log.txt
> CI: fix ci_entrypoint_gpu-operator test_operatorhub()

- toolbox/gpu_operator.py
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: gpu-operator-certified
namespace: openshift-operators
spec:
channel: "1.5.2" <-- wrong channel (this is the version)
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/20625/rehearse-20625-periodic-ci-openshift-psap-ci-artifacts-release-4.6-gpu-operator-e2e-152/1420294373391732736/artifacts/gpu-operator-e2e-152/nightly/artifacts/009__gpu_operator__deploy_from_operatorhub/gpu_operator_sub.yml
> toolbox: gpu_operator: deploy_from_operatorhub: fix channel/version mismatch

- roles/check_deps/tasks/main.yml
- roles/gpu_operator_run_gpu-burn/files/gpu_burn_pod.yml
- roles/gpu_operator_run_gpu-burn/tasks/main.yml
- roles/gpu_operator_wait_deployment/tasks/main.yml
With OCP 4.9, the `hostname` label changed from
```
"kubernetes.io/hostname": "ip-10-0-144-116",
```
to
```
"kubernetes.io/hostname": "ip-10-0-144-116.us-west-2.compute.internal",
```
GPU Burn relies on node label to be forcefully scheduled on all the
nodes with GPUs (to ensure that all the GPUs of all the nodes are
able to run CUDA workload).
> gpu_operator_run_gpu-burn: adjust hostname label on OCP >= 4.9

- roles/cluster_ensure_machineset/defaults/main/config.yml
- toolbox/cluster.py
Before this change, not specifying the base machineset would cause an
error because the ansible code treated an empty "" string differently
from an unset variable altogether.
This change makes it so the toolbox script leaves the base_machineset
variable empty, rather than have it be an empty string
> Better handling of empty base_machineset

- roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml
- roles/gpu_operator_bundle_from_commit/tasks/build_bundle.yml
- roles/gpu_operator_bundle_from_commit/tasks/build_validator.yml
- roles/gpu_operator_bundle_from_commit/tasks/main.yml
- roles/gpu_operator_bundle_from_commit/tasks/prepare.yml
- roles/gpu_operator_bundle_from_commit/templates/build_validator.yml.j2
- roles/gpu_operator_bundle_from_commit/templates/operator_bundle_image_builder_pod.yml.j2
- roles/gpu_operator_bundle_from_commit/vars/main/resources.yml
This PR builds the GPU Operator validator image, as part of `gpu_operator_bundle_from_commit`.
This is mandatory for testing the single-namespace PR https://github.com/openshift-psap/ci-artifacts/pull/242/commits, as modifications are done in this controller.
This can be useful in the future as well for testing modifications of the `node-status-exporter` metrics (same code-base)
> gpu_operator_bundle_from_commit: also build the validator image

- roles/gpu_operator_run_gpu-burn/tasks/main.yml
- roles/gpu_operator_run_gpu-burn/templates/gpu_burn_pod.yml
- roles/gpu_operator_run_gpu-burn/vars/main/resources.yml
SImple refactoring of the code to improve readability and avoid having 4.9-specific hooks (node name != hostname)
> gpu_operator_run_gpu-burn: use 'template' and remove 4.9-specific code hook

- .github/workflows/revert-testing.yml
This PUSH Github action will revert the last commit of a PR being
merged if its message starts with '[TEST TMP]'.
This allows running custom PR tests in OpenShift CI, without affecting
the routes taken by the nightly CI.
> .github/workflows/revert-testing.yml: new post-push action to remove tmp test commits

- roles/gpu_operator_run_gpu-burn/files/gpu-burn/LICENSE
- roles/gpu_operator_run_gpu-burn/files/gpu-burn/Makefile
- roles/gpu_operator_run_gpu-burn/files/gpu-burn/README.md
- roles/gpu_operator_run_gpu-burn/files/gpu-burn/compare.cu
- roles/gpu_operator_run_gpu-burn/files/gpu-burn/gpu_burn-drv.cpp
- roles/gpu_operator_run_gpu-burn/files/gpu_burn_cm_entrypoint.yml
- roles/gpu_operator_run_gpu-burn/tasks/main.yml
- roles/gpu_operator_run_gpu-burn/templates/gpu_burn_pod.yml
- roles/gpu_operator_run_gpu-burn/vars/main/resources.yml
This avoid any external dependency, instead of relying on my Github:
```
GITHUB_REPO=kpouget/gpu-burn
REF=471cc9b3ea3967a4d7bec698ec768df80344504a # kpouget/ci-friendly
SRC=https://raw.githubusercontent.com/$GITHUB_REPO/$REF
```
or any manually-generated image as it was the case before this ^^^ update
> gpu_operator_run_gpu-burn: store the gpu-burn sources within the role

- roles/gpu_operator_bundle_from_commit/defaults/main/config.yml
- roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_bundle.yml
- testing/nightly/gpu-operator.sh
This PR updates the GPU Operator CI to test the [single-namespace refactoring](https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/287).
The goal of this PR is to update the testing to code
1. to keep working with already-released versions, in the nightly testing 
2. to keep working with the `master` branch of the GPU Operator, when the refactoring will be merged.
The last tests showed that these goals are now reached:
* [gpu-operator-commit](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/242/pull-ci-openshift-psap-ci-artifacts-master-gpu-operator-commit/1432630008228089856/artifacts/gpu-operator-commit/presubmit-commit/artifacts/) passed (testing of the refactoring branch)
* [gpu-operator-e2e - …
> Test single-namespace GPU Operator

- roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml
- testing/prow/gpu-operator.sh
Previous behavior relying on the image SHA was causing a race condition in the nightly CI ...
> gpu_operator_bundle_from_commit: use temporary updated driver image

- roles/gpu_operator_get_csv_version/tasks/main.yml
- roles/gpu_operator_wait_deployment/meta/main.yml
commit a2c17d064c48e99583b20aeaa3dd129821d08977
Search for GPU operator CSV using a more generic label
Previously the `operators.coreos.com/gpu-operator-certified.{{ gpu_operator_operator_namespace }}`
label was used to find the GPU operator's CSV file. This label is being
automatically generated by OLM from the subscription using this code:
https://github.com/operator-framework/operator-lifecycle-manager/blob/20ded32d2260a8f1eeb594b9ec2147ad0134cfc6/pkg/controller/operators/adoption_controller_test.go#L107
It's possible to see that the `gpu-operator-certified` part of the label is not set in
stone, and is actually just taken from the Subscription's `.spec.name`
field.
This change makes it so the ansible role will dynamically generate this
label in a similar manner to OLM, to allow the …
> Add support for different GPU operator subscription .spec.name

- docs/ci/files.rst
- roles/check_deps/tasks/main.yml
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml
- roles/nfd_operator_deploy_from_operatorhub/tasks/main.yml
- testing/prow/gpu-operator.sh
- testing/run
Functions `_warning` and `_expected_fail` are used to track information into `${ARTIFACT_DIR}`, so that `ci-dashboard` will be able to parse it and display it in the GPU Operator dashboard:
- `_warning` will end up as messages below the test line (eg, `WARNING: Driver Toolkit image is not valid, using entitled-build fallback`)
- `_expected_fail` will be used to count the number of expected step failures (eg, ` if cluster doesn't have NFD labels (expected fail), deploy NFD`)
- and updating `$ARTIFACT_DIR/FLAKE` and `$ARTIFACT_DIR/<toolbox step>/FLAKE` here and there to be able to store mutiple messages (one per line)
-
> testing: prow/gpu-operator: fix DTK+entitlement handling and improve artifacts logging

- testing/prow/gpu-operator.sh
Fixing this:
```
+ MINI_POD_SPEC='{"apiVersion": "v1", "kind":"Pod","metadata":{"name":"test"},"spec":{"containers":[{"name":"cnt"}]}}'
+ DTK_IMAGE=image-registry.openshift-image-registry.svc:5000/openshift/driver-toolkit:latest
++ oc debug --quiet -f /dev/fd/63 --image=image-registry.openshift-image-registry.svc:5000/openshift/driver-toolkit:latest -- cat /etc/driver-toolkit-release.json
+++ echo '{"apiVersion": "v1", "kind":"Pod","metadata":{"name":"test"},"spec":{"containers":[{"name":"cnt"}]}}'
Error from server (NotFound): namespaces "ci-op-3nkbszr2" not found
```
> testing: prow/gpu-operator: fix dtk_image_is_valid

- roles/benchmarking_deploy_coco_dataset/files/entrypoint.sh
- roles/benchmarking_deploy_coco_dataset/tasks/main.yml
- roles/benchmarking_deploy_coco_dataset/templates/pod.yml.j2
- testing/prow/gpu-operator.sh
- testing/recipes/run_cocodataset_nvidiadl_ssd.sh
- toolbox/benchmarking.py
Downloading from the private mirror is for nighly/repetitive testing,
for a one-shot download, no need to rely on our private mirror + its client cert.
Tested on my local cluster.
> benchmarking_deploy_coco_dataset: make the client-cert optional and download from upstream

- roles/gpu_operator_get_csv_version/tasks/main.yml
The gpu-addon CI uses the ci-artifact's toolbox "gpu_operator wait_deployment" command which used to assume that the GPU-operator's `ClusterServiceVersion` would have a particular label. It turned out that this label is not constant and actually dependent on the `.spec.name` of the `Subscription` that triggered the creation of that CSV. So I adjusted the script to look for the gpu operator `Subscription` and determine the label that we need to look for according to that `Subscription`'s `.spec.name`.
The issue is in the "look for the gpu operator subscription" part - the gpu operator subscription has a different `.metadata.name` depending on how it's deployed (e.g. add-on vs something else). So my code would simply look for any `Subscription` containing the string "gpu-operator" (and it …
> Find gpu-operator subscriptions with `.spec.name` rather than `.metadata.name`

- testing/prow/entitle.sh
- testing/prow/gpu-operator.sh
- testing/prow/nfd-operator.sh
- testing/prow/sro.sh
* `testing/prow/entitle.sh: mark the failure of 'entitlement test_cluster' as expected`
---
* `testing/prow/nfd-operator.sh: mark the failure of 'nfd has_labels' as expected`
---
* `testing/prow/sro.sh: mark the failure of 'nfd has_labels' as expected`
---
* `testing/prow/sro.sh: mark 'NFD missing from operatorhub' as a warning`
---
* `testing/prow/gpu-operator.sh: remove mention that NFD is not available in 4.9 OperatorHub`
---
See https://github.com/openshift-psap/ci-dashboard/pull/37 for the `ci-dashboard` part of it
> Improve expected failure tracking

- testing/osde2e/gpu-addon.sh
- testing/recipes/run_osde2e_gpu_addon.sh
junit file name was generated in a way that was problematic. was including command arguments and flags.
This commit solves the issue, and all junit reports will be saved properly.
> Fix: osde2e flow was missing xml files

- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_bundle.yml
- roles/gpu_operator_wait_deployment/tasks/main.yml
- roles/gpu_operator_wait_deployment/tasks/metrics.yml
* `gpu_operator_wait_deployment: metrics: use version("1.8.0", ">=") for version checking`
---
* `gpu_operator_deploy_from_operatorhub: deploy_from_bundle: remove duplicate namespace monitoring label`
---
* `gpu_operator_wait_deployment: metrics: remove duplicate namespace monitoring label`
---
* `gpu_operator_wait_deployment: metrics: add namespace monitoring label only in v1.8.x`
---
* `gpu_operator_wait_deployment: metrics: do not check namespace monitoring`
The operator always takes care of it
---
> gpu_operator: metrics: do not check namespace monitoring

- roles/benchmarking_deploy_coco_dataset/tasks/main.yml
- roles/benchmarking_deploy_coco_dataset/templates/pod.yml.j2
- roles/benchmarking_run_nvidiadl_ssd/tasks/main.yml
- roles/benchmarking_run_nvidiadl_ssd/templates/nvidiadl-ssd-pod.yml.j2
- testing/recipes/run_cocodataset_nvidiadl_ssd.sh
This PR stores the YAML definition of the resources used to 1) download the COCO dataset and 2) trigger the benchmark
into dedicate files, so that it's easier for anyone to re-execute these steps outside of the CI, and without `ci-artifacts` toolbox.
See the files `00x` in these two directories:
- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/301/pull-ci-openshift-psap-ci-artifacts-master-test-commit/1469245167625048064/artifacts/test-commit/test-commit/artifacts/recipes_run_cocodataset_nvidiadl_ssd_download_twice_benchmark_twice/014__benchmarking__run_nvidiadl_ssd/
- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/301/pull-ci-openshift-psap-ci-artifacts-master- …
> benchmarking: make the execution easier to reproduce

- testing/osde2e/gpu-addon.sh
- testing/run
- Moved all artifacts generated by toolbox into a subdir inside ARTIFACT_DIR `ci-artifacts`
- Because of a bug in osde2e testing, the new `ci-artifacts` is missing all of its sud-dirs. Added a `ci-artifacts.tar.gz` file. This file should contain all artifacts and be visible in prow.
- fixed broken junit files due to traps in other scripts.
test-path: recipes run_osde2e_gpu_addon
> osde2e addon related tweaks

- roles/gpu_operator_bundle_from_commit/templates/build_validator.yml.j2
- roles/gpu_operator_bundle_from_commit/templates/operator_image_builder_pod.yml.j2
The GPU Operator Master branch testing (`ci-artifacts` side) got broken following the merge of this commit: https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/370
> gpu_operator_bundle_from_commit: use golang 1.17 to build the GPU Operator

- testing/prow/nto.sh
Fetch a custom version of golang for NTO e2e tests.
> Add setup_golang() function to nto.sh

- subprojects/deploy-cluster/cluster_sno.mk
- subprojects/deploy-cluster/entitlement.mk
- subprojects/deploy-cluster/utils/entitlement/cluster-wide.entitlement.machineconfigs.yaml.template
SNO clusters have a `master,worker` node, which requires a `role:
master` to receive MachineConfigs.
If we scale up the cluster with new nodes, they'll only have the `worker` role, so we need both `master` and `worker` objects to cover them all.
> [deploy-cluster] Deploy entitlement on master and workers on SNO

- roles/gpu_operator_wait_deployment/tasks/metrics.yml
Cherry picked from https://github.com/rh-ecosystem-edge/ci-artifacts/pull/6
```
Author: Mateusz Kowalski
```
---
This commit changes references from the `app=prometheus` label to the
`prometheus=k8s`. This is because prometheus-operator deprecates the
`app` label in 0.48.0 and removes it in 0.50.
As a consequence, the current label filter does not work anymore in OCP
4.10. We are moving to `prometheus=k8s` as this is the one that is
present in OCP 4.6 and later, which are supported releases for the GPU
Operator.
Relates-to: https://github.com/openshift/cluster-monitoring-operator/pull/1388
> Do not use deprecated app=prometheus label (#6)

- callback_plugins/human_log.py
- roles/cluster_deploy_operator/tasks/main.yml
- roles/entitlement_deploy/tasks/main.yml
Already merged in https://github.com/rh-ecosystem-edge/ci-artifacts/pull/10
---
* `cluster_deploy_operator: fix 'Wait for the ClusterServiceVersion install to complete'`
If the `.status.phase` of the CSV is empty (eg, right after its
creation), we should wait further, and not exit (and fail)
immediately.
This bug will be fixed:
```
2022-01-25 23:52:02,687 p=5430 u=edge-ci-runner n=ansible | roles/cluster_deploy_operator/tasks/main.yml:257
2022-01-25 23:52:02,687 p=5430 u=edge-ci-runner n=ansible | TASK: cluster_deploy_operator : Wait for the ClusterServiceVersion install to complete
2022-01-25 23:52:02,687 p=5430 u=edge-ci-runner n=ansible |
2022-01-25 23:52:02,687 p=5430 u=edge-ci-runner n=ansible | <command> oc get ClusterServiceVersion/gpu-operator-certified.v1.9.0 …
```
> Multiple bug fixes

- roles/cluster_deploy_operator/tasks/main.yml
- roles/cluster_deploy_operator/templates/subscription.yml.j2
- roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml
- roles/gpu_operator_deploy_from_operatorhub/templates/020_operator_sub.yml.j2
- roles/gpu_operator_wait_deployment/tasks/main.yml
This PR fixes the few ansible-lint warning that were introduced while the linter Action was down.
They all relate to this [rule](https://ansible-lint.readthedocs.io/en/latest/default_rules.html#var-naming):
```
var-naming
All variables should be named using only lowercase and underscores
```
> Fix ansible-linter warnings

- subprojects/deploy-cluster/entitlement.mk
When no entitlement.pem is given, makes sure the cluster-deployment tool does not get stuck.
> Fixed master entitlement hang

- toolbox/_common.py
subprocess makes reusing the Toolbox easier.
Signed-off-by: François Cami <fcami@redhat.com>
> _common.py: switch back to subprocess

- subprojects/sno-snapshot/README.md
- subprojects/sno-snapshot/requirements.txt
- subprojects/sno-snapshot/src/common.py
- subprojects/sno-snapshot/src/rollback.py
- subprojects/sno-snapshot/src/snapshot.py
This WIP sub-project aims at providing a snapshot/rollback capability to a single-node OpenShift cluster running on AWS.
Snapshotting
------------
```
./snapshot.py
Creates the snapshot of the current state of the SNO node, if no
snapshot already exists.
./snapshot.py --wait
Creates or awaits for the completion of the current AWS
snapshot. This takes several minutes to complete, but 1/ the
cluster is available during the snapshot creation and 2/ any
changes performed after the snapshot creation time will not be
included in the snapshot.
./snapshot.py --delete
Deletes the AWS snapshot associated with this cluster, so that a
new one can be created.
```
*Open questions*:
- Should the node be turned off before triggering the snapshot?
*Todo*:
- Include a human-readable timestamp in the …
> [sno-snapshot] New subproject for OpenShift SNO Snapshot/Rollback with AWS

- roles/benchmarking_run_nvidiadl_ssd/defaults/main/config.yml
- roles/benchmarking_run_nvidiadl_ssd/files/entrypoint.sh
- roles/benchmarking_run_nvidiadl_ssd/tasks/main.yml
- roles/benchmarking_run_nvidiadl_ssd/templates/nvidiadl-ssd-pod.yml.j2
- testing/recipes/run_cocodataset_nvidiadl_ssd.sh
- testing/wdm/gpu-operator.yml
- toolbox/benchmarking.py
Get nvidiadl ssd training benchmark working with new auto-updated image
NOTE: `test-path: recipes run_cocodataset_nvidiadl_ssd`
> Automation for running NVIDIA MLPerf SSD training

- roles/cluster_deploy_operator/templates/subscription.yml.j2
Note that this typo did not affect the good behavior of the role, as
long as no two operators were deployed in the same namespace.
> cluster_deploy_operator: fix typo in the subscription name

- testing/run
fixing this:
```
The connection to the server api.ci-ocp-4-10-amd64-aws-us-east-1-tlbhj.hive.aws.ci.openshift.org:6443 was refused - did you specify the right host or port?
----
|Running 'has_nfd_operatorhub': Failure
|___
ERROR: 'has_nfd_in_operatorhub' test failed, but no install script provided.
+ run_finalizers
+ '[' 0 -eq 0 ']'
+ return
/opt/ci-artifacts/src//testing/run: line 101: /logs/artifacts/FLAKE: Is a directory
Test of 'test-commit' failed. 
```
> testing: run: fix cluster_destroyed flake handling

- roles/nfd_operator_deploy_custom_commit/files/operator_image_builder_script.yml
This PR fixes the testing of NFD-operator master, which got broken because of an incompatibility between golang 1.16 and more recent version.
Instead of a hard-coded golang version 1.16, the script now parses the [version used in the image](https://github.com/openshift/cluster-nfd-operator/blob/master/Dockerfile#L2):
```
FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.11 AS builder
^^^^^^^^^^^
```
/cc @ArangoGutierrez
> nfd_operator_deploy_custom_commit: use the same golang version as in the NFD-operator repo

- roles/cluster_deploy_aws_efs/tasks/aws-efs.yaml
So that it works when the cluster isn't in the default region
> cluster_deploy_aws_efs: add 'region' to AWS queries

- testing/ods/jh-at-scale.sh
> RHODS: disable `jh-at-scale` while it's leaking AWS resources

- build/Dockerfile
* `build/Dockerfile: remove trailing/ in $HOME`
---
* `build/Dockerfile: ensure that ocm is an ELF binary`
This should prevent this runtime error:
```
+ bash -c '
set -o errexit
set -o nounset
OCM_TOKEN=$(cat "$PSAP_ODS_SECRET_PATH/ocm.token" | grep "^${OCM_ENV}=" | cut -d= -f2-)
echo "Login in $OCM_ENV with token length=$(echo "$OCM_TOKEN" | wc -c)"
exec ocm login --token="$OCM_TOKEN" --url="$OCM_ENV"
'
Login in staging with token length=755
/usr/local/bin/ocm: line 1: $'\r': command not found
/usr/local/bin/ocm: line 2: html: No such file or directory
/usr/local/bin/ocm: line 3: head: No such file or directory
/usr/local/bin/ocm: line 4: meta: No such file or directory
/usr/local/bin/ocm: line 5: title: No such file or directory
/usr/local/bin/ocm: line 5: middot: command not found …
```
> Update the dockerfile

- testing/ods/common.sh
The path is now exposed in the test-side, see https://github.com/openshift/release/pull/29763
> testing: ods: common: remove the hard-coded path to PSAP_ODS_SECRET_PATH

- testing/ods/jh-at-scale.sh
- testing/ods/process_ctrl.sh
- toolbox/_common.py
This PR adds a prefix to the `artifacts_extra_logs_dir`.
We use it to distinguish more easily (and programmatically) if a command ran against the driver cluster or the sutest cluster.
> toolbox: _common.py: accept ARTIFACT_TOOLBOX_NAME_PREFIX as a prefix to the artifacts_extra_logs_dir name

- roles/benchmarking_deploy_coco_dataset/files/entrypoint.sh
- roles/benchmarking_deploy_coco_dataset/tasks/main.yml
* `benchmarking_deploy_coco_dataset: make the download quiet`
---
* `benchmarking_deploy_coco_dataset: store the pod description`
Instead of its logs
---
/cc @kpouget
> benchmarking_deploy_coco_dataset: fix minor details

- roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-psap-simplenotebook.robot
This PR removes the `Clean up the files and folders we created` step from the simple test robot.
This steps often fails, and it isn't relevant for us (we delete the PVCs after the testing).
> rhods_test_jupyterlab: test-jupyterlab-psap-simplenotebook: remove 'Clean up the files and folders we created'

- roles/cluster_capture_environment/tasks/main.yml
- roles/cluster_destroy_osd/defaults/main/config.yml
- roles/cluster_destroy_osd/tasks/main.yml
- roles/rhods_test_jupyterlab/tasks/main.yml
- testing/ods/ocp_cluster.sh
- testing/ods/osd_cluster.sh
- testing/ods/process_ctrl.sh
* `rhods_test_jupyterlab: improve 'Show failed tests'`
---
* `rhods_test_jupyterlab: store the test-case and exclude-tags in Matbench's settings`
---
* `rhods_test_jupyterlab: mute old ev/artifacts cleanup`
---
* `rhods_test_jupyterlab: mute artifacts extraction`
---
* `cluster_destroy_osd: downscale the cluster before destroying it`
---
* `cluster_capture_environment: capture the cluster's nodes and machines`
---
* `testing: ods: process_ctrl: use sigTERM instead of sigKILL to terminate bg processes`
---
* `testing: ods: ocp_cluster: better call save_install_artifacts on failure`
---
* `testing: ods: ocp/osd clusters: add prefix to toolbox command artifacts`
---
> RHODS: minor updates

- testing/ods/autoscaling/clusterautoscaler.yaml
- testing/ods/autoscaling/machineautoscaler.yaml
- testing/ods/common.sh
- testing/ods/ocp_cluster.sh
- testing/ods/osd_cluster.sh
Tested in https://github.com/openshift-psap/ci-artifacts/pull/406, but OSD scaling not working yet because of missing capabilities.
> Failed to create cluster: unable to create cluster: status is 400, identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is '917fc84f-bdd8-42b7-883a-c96858134146': Autoscaling is only allowed for clusters with the 'autoscale_clusters' capability
/cc @kpouget
> testing: ods: {ocp,osd}_cluster: add auto-scaling support

- testing/ods/common.sh
This PR properly disables the auto-scaler enablement.
The previous value (`0`) enabled the auto-scaling, so I added a
comment to make it clear that not-empty is enabled.
/cc @fcami 
/approve
> testing: ods: common: properly disable ENABLE_AUTOSCALER

- roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-psap-simplenotebook.robot
- roles/rhods_test_jupyterlab/tasks/main.yml
- testing/ods/generate_matrix-benchmarking.sh
- toolbox/_common.py
* `toolbox: _common.py: do not generate artifact_extra_logs_dir/exit_code`
This file is redundant with FAILURE generated in case of failure.
---
* `rhods_test_jupyterlab: do not keep our canary file 'os-release' in the artifacts`
This file is added to the bucket to avoid it being empty and making
some copy fail because of it.
We do not want to keep it in the artifacts.
---
* `rhods_test_jupyterlab: robot test: refactor to use variables and do not call 'Begin/End Web Test'`
- Variables make a cleaner separation between configuration and
execution
- Being/End Web Test ROBOT keywords were doing things out of our view,
like connecting to RHODS/JupyterHub, and deleting the Notebook.
---
* `rhods_test_jupyterlab: robot test: remove the call to 'Can Close Notebook when done'`
We want to keep the …
> RHODS: update the robot test

- roles/rhods_test_jupyterlab/defaults/main/config.yml
- roles/rhods_test_jupyterlab/files/entrypoint.sh
- roles/rhods_test_jupyterlab/templates/rhods-ci.yaml
- testing/ods/common.sh
- testing/ods/jh-at-scale.sh
- toolbox/rhods.py
- Sleep for JOB_COMPLETION_INDEX*SLEEP_FACTOR seconds to avoid DDoSing Oauth.
- Un-hardcode SLEEP_FACTOR (time to wait in between users).
- Define rhods_test_jupyterlab_ods_sleep_factor from SLEEP_FACTOR.
- & sleepfactor: test 0.2
> rhods_test_jupyterlab: Add test Pod startup delay

- roles/rhods_test_jupyterlab/tasks/main.yml
Previously, all pods, pvcs, and events were cleaned from the rhods
notebook namespace.
Attempt to remove only objects created for our test users.
Signed-off-by: François Cami <fcami@redhat.com>
> rhods_test_jupyterlab: only remove our testusers objects

- roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-run-notebook.robot
- testing/ods/common.sh
- testing/ods/jh-at-scale.sh
* `testing: ods: jh-at-scale: reorganize run_multi_cluster to ease reuse`
---
* `rhods_test_jupyterlab: better catch errors in 'Spawn a Notebook'`
Avoid false-positives in this test, by trying to run something in the
notebook after the spawn.
---
/cc @kpouget
> testing: ods: jh-at-scale: reorganize run_multi_cluster to ease reuse

- testing/ods/common.sh
The `_` is a special character for naming K8s resources, so RHODS
rewrites it into `-5f`. Better stay without special characters.
/cc @fcami FYI
> testing: ods: common: use psapuser as username prefix

- roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-run-notebook.robot
Testing was broken because of the missing (double) space ...
/cc @kpouget
> rhods_test_jupyterlab: fix call to 'Suite Teardown  Tear Down'

- roles/cluster_undeploy_ldap/defaults/main/config.yml
- roles/cluster_undeploy_ldap/tasks/main.yml
- testing/ods/jh-at-scale.sh
- toolbox/cluster.py
* `cluster_undeploy_ldap: also undeploy on osd/rosa`
The role `cluster_undeploy_ldap` was only undeploying the LDAP setup
in OCP, and not in OSD/ROSA.
This commit fixes this missing point.
---
* `testing: ods: jh-at-scale: undeploy LDAP after testing`
Until now, the LDAP authentication was not undeployed in the CI
testing.
This commit fixes that, so that the SUTest cluster is left in a
cleaner state.
---
> RHODS: cluster_undeploy_ldap: also undeploy on osd/rosa 

- roles/cluster_create_osd/tasks/main.yml
- roles/rhods_test_jupyterlab/files/entrypoint.sh
- roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-run-notebook.robot
- roles/rhods_test_jupyterlab/files/s3-artifacts-exporter.sh
- roles/rhods_test_jupyterlab/templates/rhods-ci.yaml
- testing/ods/generate_matrix-benchmarking.sh
- toolbox/cluster.py
* `testing: ods: generate_matrix-benchmarking: use the right ARTIFACTS_DIR`
---
* `rhods_test_jupyterlab: retry 15 times to spawn the notebook`
---
* `cluster_create_osd: set a minimum of 2 replicas for the machinepool`
With 1, OCM will complain.
---
* `rhods_test_jupyterlab: set NOTEBOOK_SPAWN_WAIT_TIME = 15 minutes`
---
* `rhods_test_jupyterlab: entrypoint: pass --exitonfailure to the Robot`
With this flag, no more test cases are executed after one failed.
---
* `rhods_test_jupyterlab: s/ARTIFACT_DIR/ARTIFACTS_DIR/ to be consistent with OpenShift CI env variable`
---
> RHODS: various updates

- roles/rhods_wait_ods/defaults/main/config.yml
- roles/rhods_wait_ods/tasks/main.yml
- testing/ods/common.sh
- testing/ods/jh-at-scale.sh
* `testing: ods: jh-at-scale: look up in the cluster the image tag to preload`
This part was failing on OSD, as the addon is installing the "latest"
version of RHODS and not a specific one as we do in OCP.
---
* `rhods_wait_ods: wait for RHODS images to be loaded`
---
/cc @kpouget
> RHODS: wait for RHODS images to be loaded and look up in the cluster the image tag to preload

- roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-run-notebook.robot
Tested in https://github.com/openshift-psap/ci-artifacts/pull/420#issuecomment-1186138381.
/cc @kpouget
> rhods_test_jupyterlab: robot: Wait 20 secs before retrying (45 times) to spawn the notebook

- roles/rhods_test_jupyterlab/tasks/main.yml
There may be no Pods ...
/cc @kpouget
> rhods_test_jupyterlab: Get the name of the notebook Pods: ignore errors

- subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/advanced_timeline.py
- subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/error_report.py
- subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/mapping.py
- subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
* `[matrix-benchmarking-workloads/rhods-ci] mapping: do not crash when a Notebook pod wasn't created`
---
* `[matrix-benchmarking-workloads/rhods-ci] store: ignore tests skipped with exit-on-failure`
With the robot --exit-on-failure recently enabled, when a test-case
fails, the following ones won't be executed, but directly marked as
failed.
This commit skips these skipped tests from our parsing.
---
* `[matrix-benchmarking-workloads/rhods-ci] advanced_timeline: user integer index for Y axis`
---
* `[matrix-benchmarking-workloads/rhods-ci] error_report: fix images when running interactively`
---
* `[matrix-benchmarking-workloads/rhods-ci] error_report: fix style (use a dict instead of str)`
Dash doesn't like the str ...
---
* `[matrix-benchmarking-workloads/rhods-ci] error_report: group …
> [matrix-benchmarking-workloads/rhods-ci] Improve plots

- roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-run-notebook.robot
- testing/ods/common.sh
- testing/ods/notebooks/simple-notebook.ipynb
Commit 499f2983d8955c279ac70edd0798e5e8a5caed56 switched from
the s2i-generic-data-science-notebook image to the s2i-minimal
notebook image.
Revert the change to be able to run more notebooks.
Signed-off-by: François Cami <fcami@redhat.com>
> rhods_test_jupyterlab: robot: revert to the s2i-generic-data-science-notebook image

- roles/cluster_destroy_ocp/defaults/main/config.yml
- roles/cluster_destroy_ocp/tasks/main.yml
- roles/cluster_destroy_ocp/templates/metadata.json.j2
- toolbox/cluster.py
This commit updates the `cluster_destroy_ocp` to look up the cluster's
REGION and TAG_ID with `oc` (from the `machine` AWS specs).
These two values are then passed to `openshift-install` to destroy the
cluster.
This version of the toolbox can only run if the `--confirm` flag is
passed.
---
Tested locally.
/cc @fcami
> cluster_destroy_ocp: allow passing no option to delete the local cluster

- roles/rhods_wait_ods/defaults/main/config.yml
Without this, the automation may try to spawn notebooks before these
images are built, and RHODS dashboard refuses to go to JupyterLab when
these images are missing.
Fixes: PSAP-806
/cc @fcami
> RHODS: rhods_wait_ods: default: also wait for tensorflow and pytorch images

- testing/run
The PR json file contains the title, description, commit and base
commit, which are useful information about the version of code being
tested.
The comments of the PR contain, among other things, the `/test`
command that was used to trigger the testing. Soon we'll use this to run
different configurations of the test, eg:
```
/test ods-jh-on-ocp TEST=1 VALUE=2
```
---
Tested in #450: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/450/pull-ci-openshift-psap-ci-artifacts-master-ods-get-cluster/1550354756239626240/artifacts/get-cluster/test/artifacts/
> testing: run: download the PR and its comment into the artifacts

- testing/run
This breaks the rehearsals from openshift/release.
> testing: run: do not crash when the pull request data cannot be fetched

- subprojects/cloud-watch/cleanup-rhods-zombie.py
Otherwise the command may delete all the CI clusters ...
/cc @kpouget
> [cloud-watch] Refuse to run with --delete but without --ci-delete-older-than

- roles/rhods_deploy_ods/tasks/main.yml
This commit mocks up the GPU images of RHODS. They are normally built in the cluster, and this takes more than 1h. We don't use these images at the moment, so no need to build them.
If ever we get to use them, we'll certainly prefer storing them in a _private_ quay repo and populate them from there.
/cc @fcami
> rhods_deploy_ods: delete the GPU image builds and mock them up

- subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/error_report.py
- subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
This PR adds further information in the error report about the test that was executed.
/cc @fcami 
```
matbench-data-url: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/460/pull-ci-openshift-psap-ci-artifacts-master-ods-get-cluster/1551835589391683584/artifacts/get-cluster/test/artifacts/
```
Example:
---
* PR[ openshift-psap/ci-artifacts #462 ](https://github.com/openshift-psap/ci-artifacts/pull/462)RHODS: use a dedicated image for the artifacts exporter side-car
```
This PR creates a dedicated image for artifacts exporter side-car container of the `test_jupyterlab` test.
This is a cleaner design, and it solves the issue that, until now, all the simulated users had to install `s3cmd` package and download `yq` from Github. …
```
> [matrix-benchmarking-workloads/rhods-ci] error_report: Improve with further info about the test

- testing/ods/cleanup/zombies.sh
Before this fix, 'wc -l' outputs the name of the file after the line count
/cc @kpouget
> testing: ods: cleanup/zombies: properly compute the number of clusters deleted

- testing/prow/_logging.sh
Already used in testing/benchmarking/run_mlperf_ssd.sh but not implemented.
Function was missing in this nightly test: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-master-4.10-e2e-mlperf-ssd/1552066448631795712/artifacts/e2e-mlperf-ssd/nightly/build-log.txt
/cc @kpouget
> testing: prow: _logging: add _flake function

- roles/rhods_test_jupyterlab/defaults/main/config.yml
- roles/rhods_test_jupyterlab/files/s3-artifacts-exporter.sh
- roles/rhods_test_jupyterlab/tasks/main.yml
- roles/rhods_test_jupyterlab/templates/rhods-ci.yaml
- roles/utils_build_push_image/tasks/build_image.yml
- roles/utils_build_push_image/tasks/main.yml
- roles/utils_build_push_image/templates/image_buildconfig.yml.j2
- testing/ods/common.sh
- testing/ods/images/Containerfile.s3_artifacts_exporter
- testing/ods/jh-at-scale.sh
- toolbox/rhods.py
This PR creates a dedicated image for artifacts exporter side-car container of the `test_jupyterlab` test.
This is a cleaner design, and it solves the issue that, until now, all the simulated users had to install `s3cmd` package and download `yq` from Github.
/cc @fcami
> RHODS: use a dedicated image for the artifacts exporter side-car

- roles/rhods_test_jupyterlab/files/ods-ci/test-jupyterlab-run-notebook.robot
- roles/rhods_test_jupyterlab/templates/rhods-ci.yaml
- testing/ods/common.sh
- testing/ods/images/Containerfile.s3_artifacts_exporter
- testing/ods/jh-at-scale.sh
- toolbox/rhods.py
* `rhods_test_jupyterlab: receive the notebok image name from a CLI parameter`
This commit allows the `rhods_test_jupyterlab` to receive an image
name, and passes it to the ODS-CI Pods.
This avoid the duplication of the image name (image preloading vs
notebook creation), and allows the definition of the image name from
the `common.sh` property file.
---
* `testing: ods: move ODS_CI_ARTIFACTS_COLLECTED to common.sh`
This commit moves ODS_CI_ARTIFACTS_COLLECTED to common.sh, as it's not
anymore a dynamic value as it used to be.
---
* `rhods_test_jupyterlab: test-jupyterlab-run-notebook.robot: catch notebook execution errors`
This commit ensures that errors in the notebook execution are not
silently ignored.
---
> RHODS: Fail on notebook errors and define the notebook image in a single location

- build/Dockerfile
Original commit cherry-picked from https://github.com/rh-ecosystem-edge/ci-artifacts/pull/45
```
Requests to mirror.openshift.com originating from the CI worker IP
pool are now redirected to S3 buckets for cost saving.
```
`curl`'s `--location` (long for `-L`) follows this redirection.
Also add `--fail` and `--show-error` to fail explicitly on HTTP
errors.
> build: Follow redirects for mirror.openshift.com

- testing/ods/cleanup/zombies.sh
only `AWS_DEFAULT_PROFILE` must be exposed for the boto3 scripts to run :/
/cc @kpouget
> testing: ods: cleanup/zombies.sh: do not expose AWS_PROFILE

- testing/run
This PR disables the rehearsal of `ci-artifacts` tests (from
`openshift/release`).
Rehearsal (and testing) creates clusters, we don't want to waste
resources by automatically creating multiple clusters. Better merge
the `openshift/release` PR and test on demand on ci-artifacts.
> testing: run: disable PR rehearsal

- roles/rhods_notebook_ux_e2e_scale_test/tasks/main.yml
The error was muted ...
/cc @kpouget
> rhods_notebook_ux_e2e_scale_test: use right prefix to delete the notebooks at the end of the test

- testing/pr_args.sh
- testing/run
This PR fetches extra configuration settings from the PR body and test trigger comment.
The syntax is: `/env key=value` or `/test <prow_test> <inline settings>`, example:
```
/test test-pr-no-cluster hello world
/env hello=world
/env toto=yes
```
which generates the [following file](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/491/pull-ci-openshift-psap-ci-artifacts-master-test-pr-no-cluster/1565963447680634880/artifacts/test-pr-no-cluster/test-pr/artifacts/variable_overrides) in `${ARTIFACT_DIR}/variable_overrides`
```
PR_POSITIONAL_ARGS='hello world'
test_path='recipes test'
hello='world'
toto='yes'
```
This file can then be sourced or parsed from the test.
> testing: pr_args: new script to fetch the PR test arguments

- testing/pr_args.sh
As the variable is not exposed in the environment variables.
/cc @kpouget
> testing: pr_args: use /var instead of /env

- testing/ods/private_cluster.sh
- testing/ods/run_private_notebook_ux_e2e_scale_test.sh
This entrypoint requires two extra variables to be defined when
launching the test:
```
SUTEST_CLUSTER_NAME must be set with the base name of the private cluster
SUTEST_CLUSTER_USER_NAME must be set with the username to use to log into the private cluster
```
Example:
```
/test ods-nb-ux-on-private
/var SUTEST_CLUSTER_NAME my.cluster.base.name
/var SUTEST_CLUSTER_USER_NAME my_username
```
> testing: ods: run_private_notebook_ux_e2e_scale_test: new entrypoint to test a private cluster

- roles/rhods_notebook_api_scale_test/files/entrypoint/locustfile.py
- roles/rhods_notebook_api_scale_test/files/entrypoint/run_locust_on_laptop.sh
- testing/ods/clusters.sh
/var NOTEBOOK_TEST_FLAVOR=api-level
/var ODS_CATALOG_IMAGE_TAG=1.18.0-6
> rhods_notebook_api_scale_test: disable REUSE_COOKIES by default when running on the cluster

- subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/error_report.py
- testing/ods/config_clusters.sh
- testing/ods/sizing/machines
- testing/ods/sizing/sizing
/var CI_DEFAULT_CLUSTER_TYPE=ocp
/var OCP_VERSION=4.11.9
/var OCP_SUTEST_COMPUTE_MACHINE_TYPE=m6i.2xlarge
/var OCP_MASTER_MACHINE_TYPE=m6i.2xlarge
/var ODS_CATALOG_IMAGE_TAG=1.18.0-7
/var ODS_CI_NB_USERS=200
/var ODS_SLEEP_FACTOR=5
/cc @kpouget
> RHODS: test 1.18

- testing/ods/clusters.sh
- testing/ods/generate_matrix-benchmarking.sh
- testing/ods/run_notebook_scale_test_on_private.sh
- testing/pr_args.sh
/var clusters.create.ocp.control_plan.type=m6i.2xlarge
/var clusters.create.ocp.compute.type=m6i.2xlarge
/var rhods.catalog.tag=v1190-7
/var tests.notebooks.users.count=5
/var test.notebooks.users.sleep_factor=2
> RHODS: test 1.19

- roles/rhods_notebook_ux_e2e_scale_test/tasks/main.yml
- testing/ods/config.yaml
/var clusters.create.ocp.control_plane.type=m6i.2xlarge
/var clusters.create.ocp.compute.type=m6i.2xlarge
/var rhods.catalog.tag=v1180-8 
/var tests.notebooks.users.count=300
/var tests.notebooks.users.sleep_factor=2
> RHODS: test RHODS

- testing/model-mesh/command_args.yaml
- testing/model-mesh/config.yaml
- testing/model-mesh/locust.sh
/cc @fcami 
This PR adds an entrypoint stub for running Locust against RHODS/ODH model-mesh server.
Tested in https://github.com/openshift-psap/ci-artifacts/pull/581
> testing: model-mesh: locust: new entrypoint

- roles/cluster_deploy_nginx_server/tasks/main.yml
- roles/cluster_deploy_nginx_server/templates/deploy_nginx.yaml.j2
- roles/cluster_deploy_nginx_server/templates/nginx.conf.j2
- roles/cluster_deploy_nginx_server/vars/main/resources.yml
- add OCP-provided TLS certs for nginx
- add HTTPS nginx configuration, service and route For now, this is not configurable (e.g. always-on).
Signed-off-by: Kevin Pouget <kpouget@redhat.com>
Signed-off-by: François Cami <fcami@redhat.com>
> cluster_deploy_nginx_server: add https

- .gitignore
- subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/horreum_lts_store.py
This PR adds functionality to the `rhods-notebook-ux` store, allowing it to parse previous results and present them for storage.
This is blocking [#63 from matrix-benchmarking](https://github.com/openshift-psap/matrix-benchmarking/pull/63) from being merged.
> Update Store to Parse for Horreum

- subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py
- testing/notebooks/generate_matrix-benchmarking.sh
This PR adds an option to the `matbench parse` section of `generate_matrix-benchmarking.sh` so it saves the Horreum payload to `lts_payload.json`
> Add Horreum JSON Generation to testing

- subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/horreum_lts_store.py
- subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py
This PR adds start/end times to MatrixEntries, parsed from `_ansible.log`.
This also updates the LTS payload generator to use these times
> Add Start/End times to MatrixEntries

- subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/horreum_lts_store.py
- subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/prom.py
- subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py
This PR is meant to start reducing the amount of information that is going to be stored in Horreum.
Example output:
```json5
{
"metadata": {
"test": "rhods-notebooks-ux",
"start": "2023-04-20T10:21:00-04:00", //Start time of test, tz info automatically generated
"end": "2023-04-20T10:21:00-04:00" //End time of test, tz info automatically generated
},
"data": {
"rhods_version": 1.21.0", //RHODS version that the test was using
"ocp_version": "4.12.9", //OpenShift version that was the cluster under test was using
"users": [
{
"hostname": "host0", //hostname of the node that ran the pod
"steps": [
{
"name": "<NAME OF STEP>",
"duration": 12, //Seconds taken to complete step
"status": "FAILED" //Can be COMPLETE or FAILED,
"substeps": [] //Optional, contains sub steps for "Wait for Notebook …
```
> Rhods-notebooks-ux: Limit Horreum data output

- roles/load_aware_deploy_trimaran/defaults/main/config.yml
- roles/load_aware_deploy_trimaran/files/cluster-monitoring-config.yaml
- roles/load_aware_deploy_trimaran/files/trimaran.yaml
- roles/load_aware_deploy_trimaran/meta/main.yml
- roles/load_aware_deploy_trimaran/tasks/main.yml
- roles/load_aware_deploy_trimaran/vars/main/resources.yml
- testing/load-aware/test.py
- toolbox/__init__.py
- toolbox/load_aware.py
This should cover the basics of deploying the Trimaran scheduler.
Trimaran can be deployed to enable load aware scheduling using:
```
./run_toolbox.py load_aware deploy_trimaran
```
> load-aware: add ansible role to deploy Trimaran scheduler

- OWNERS
- testing/utils/configure.sh
- testing/utils/openshift_clusters/ocp_cluster.sh
- refuse to create clusters without a `TicketId`
- set the users' Kerberos ID as `User` tag
- define the list of users allowed to create clusters (under the PSAP AWS account)
- refuse to create clusters for users not listed
- only use the `ci-artifact` AWS account
> testing: improve cluster creation control

- roles/rhods_deploy_ods/tasks/main.yml
A small test to investigate a failing test due to ods operator panic.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/748/pull-ci-openshift-psap-ci-artifacts-main-pipelines-light/1666899339294806016/artifacts/light/gather-extra/artifacts/pods/redhat-ods-operator_rhods-operator-5d5b7f6f9-7tb54_rhods-operator_previous.log
```
...
time="2023-06-08T20:40:14Z" level=info msg="KubeFlow Deployment Completed."
time="2023-06-08T20:40:15Z" level=info msg="Reconciling KfDef resources. Request.Namespace: redhat-ods-applications, Request.Name: rhods-data-science-pipelines-operator."
E0608 20:40:15.344012       1 runtime.go:73] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] …
```
> testing: ods operator panics during deployment for pipeline test

- roles/load_aware_deploy_trimaran/files/trimaran-test-pod.yaml
- roles/load_aware_deploy_trimaran/files/trimaran.yaml
- roles/load_aware_deploy_trimaran/tasks/main.yml
- roles/load_aware_deploy_trimaran/vars/main/resources.yml
Retry grabbing the monitoring token if we see signs it doesn't look correct. Also polish the deployment tasks.
> testing: retry trimaran deploy if token looks malformed

- roles/load_aware_deploy_trimaran/.gitignore
- roles/load_aware_deploy_trimaran/defaults/main/config.yml
- roles/load_aware_deploy_trimaran/tasks/main.yml
- roles/load_aware_deploy_trimaran/templates/trimaran.yaml.j2
- roles/load_aware_deploy_trimaran/vars/main/resources.yml
- roles/load_aware_undeploy_trimaran/defaults/main/config.yml
- roles/load_aware_undeploy_trimaran/tasks/main.yml
- roles/load_aware_undeploy_trimaran/vars/main/resources.yml
- testing/load-aware/command_args.yaml
- testing/load-aware/config.yaml
- testing/load-aware/test.py
- toolbox/load_aware.py
Adds the ability to configure Trimaran's plugin and corresponding settings from the CI. Also adds the ability to change the log level. This PR should not affect the `undeploy` role. However, the `undeploy` role must have access to the generated `trimaran.yaml` that was used to deploy Trimaran or it might not be able to properly cleanup.
> load-aware: enable configuring Trimaran plugins and settings

- testing/pipelines/config.yaml
- testing/pipelines/notebooks/timed-multistage/kfp_timed_multistage.ipynb
- testing/pipelines/notebooks/timed-multistage/timed_multistage.py
It was brought up that this pipeline might be useful for testing. It has 4 parallel pipelines, each 3 interdependent stages. Each stage should take 2 minutes and generate CPU load during that time by repeatedly taking square roots.
> pipelines: sample pipeline with multiple dependent stages and fixed runtime

- requirements.txt
- roles/load_aware_scale_test/defaults/main/config.yml
- roles/load_aware_scale_test/files/load-aware-ns.yaml
- roles/load_aware_scale_test/files/scheduler.py
- roles/load_aware_scale_test/files/timeline.py
- roles/load_aware_scale_test/meta/main.yml
- roles/load_aware_scale_test/tasks/main.yml
- roles/load_aware_scale_test/vars/main/resources.yml
- testing/load-aware/command_args.yaml
- testing/load-aware/config.yaml
- testing/load-aware/test.py
- toolbox/load_aware.py
- visualizations/load-aware/store/parsers.py
This adds the role to launch load-aware scale tests according to a few different statistical distributions, specifically the Poisson. Options for gamma, uniform, normal, and a bimodal distributions are also included.
Currently this only launches test pods. The next step will be adding a real workload to the scale test.
> load-aware: role to launch load-aware scale test corresponding to Poisson distribution

- visualizations/rhods-notebooks-performance/models/lts.py
- visualizations/rhods-notebooks-performance/store/lts.py
- visualizations/rhods-notebooks/horreum_lts_store.py
- visualizations/rhods-notebooks/models/__init__.py
- visualizations/rhods-notebooks/models/prom.py
This fixes the `$schema` field being outputted as `schema_name`
```
Traceback (most recent call last):
File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/opt/ci-artifacts/src/subprojects/matrix-benchmarking/matrix_benchmarking/main.py", line 12, in <module>
import matrix_benchmarking.visualize
File "/opt/ci-artifacts/src/subprojects/matrix-benchmarking/matrix_benchmarking/visualize.py", line 4, in <module>
import matrix_benchmarking.matrix
File "/opt/ci-artifacts/src/subprojects/matrix-benchmarking/matrix_benchmarking/matrix.py", line 9, in <module>
import matrix_benchmarking.store as store
File …
```
> [Notebooks] Fix Schema on Export

- roles/load_aware/load_aware_deploy_trimaran/tasks/main.yml
- roles/load_aware/load_aware_scale_test/tasks/main.yml
If scale test fails or if the trimaran-test pod can't be scheduled, continue to dump stats, logs and cluster info.
> load-aware: always dumps statistics

- roles/wisdom/wisdom_deploy_model/templates/serving_runtime.yml.j2
- roles/wisdom/wisdom_llm_load_test/tasks/main.yml
- roles/wisdom/wisdom_llm_load_test_multiplexed/tasks/main.yml
- roles/wisdom/wisdom_llm_load_test_multiplexed/templates/llm-load-test-config.json.j2
- testing/lightspeed/command_args.yaml
- testing/lightspeed/config.yaml
- testing/lightspeed/test.py
- toolbox/wisdom.py
This PR fixes an issue in the original implementation of `roles/wisdom_llm_load_test_multiplexed`. It also switches to using command_args, though this cleanup is not yet complete. I would like to run the full suite of tests and then merge this PR as is assuming that it works. More cleanup can come in a follow-up PR.
Remaining to-dos:
- Clean up the way llm_load_test config is passed from testing/lightspeed/config.yaml is passed to llm_load_test container (may require cleanup in llm_load_test itself). Allow setting runtime/model version from testing/lightspeed/config.yaml
- Rename roles/wisdom/wisdom* to roles/lightspeed/lightspeed*
> lightspeed: update ServingRuntime and switch to using command_args

- roles/load_aware/load_aware_deploy_trimaran/tasks/main.yml
- roles/load_aware/load_aware_scale_test/tasks/main.yml
- visualizations/load-aware/plotting/error_report.py
- visualizations/load-aware/plotting/pod_times.py
- visualizations/load-aware/store/parsers.py
Always dump trimaran log after scale test and link to it in the report.
> load-aware: make trimaran log more visible

- visualizations/rhods-notebooks-performance/store/lts.py
This PR adds a default timezone to the start/end times within the JSON payloads, so it passes Horreum's datetime validation.
> rhods-perf/lts: Add timezone information to JSON payloads

- roles/cluster/cluster_prometheus_db/tasks/reset.yml
- testing/notebooks/prepare_driver.sh
- testing/notebooks/prepare_sutest.sh
otherwise, 'oc delete' may block for hours :/
> cluster_prometheus_db: Delete Prometheus Pod: add a timeout of 60s

- roles/cluster/cluster_deploy_operator/tasks/deploy_cr.yml
…
otherwise it will be deployed in the active namespace
and that won't work in the CI
> cluster_deploy_operator: deploy_cr: add a namespace parameter when deploying the CR

- roles/load_aware/load_aware_deploy_trimaran/tasks/main.yml
- roles/load_aware/load_aware_scale_test/tasks/main.yml
- testing/load-aware/config.yaml
- visualizations/load-aware/plotting/comparison.py
- visualizations/load-aware/plotting/pod_times.py
This should fix the suggestions in #855 and #863.
> load-aware: dump trimaran log during deploy
