inventory/aws/hosts

rm unnecesary inventory var

---

playbooks/gpu-burst.yml

rm gather_debug.yml calls

---

README.md

Quickstart readme

---

README.md

enhance README

---

configs/.yamllint.conf

add yamllint.conf

---

configs/.yamllint.conf
playbooks/gpu-burst.yml
playbooks/nvidia-gpu-operator-ci.yml
roles/check_deps/tasks/main.yml
roles/nv_gpu/files/001_namespace.yaml
roles/nv_gpu/tasks/ci_checks.yml
roles/openshift_nfd/tasks/uninstall_nfd.yml
roles/openshift_node/tasks/scaleup_checks.yml
roles/openshift_odh/tasks/install_required_pkgs.yml

make yamllint happy

---

build/root/usr/local/bin/run
group_vars/all.yml
playbooks/openshift-odh-ci.yml
playbooks/openshift-psap-ci.yml
roles/openshift_nfd/tasks/main.yml
roles/openshift_nfd/tasks/uninstall_nfd.yml
roles/openshift_odh/tasks/install_required_pkgs.yml
roles/openshift_odh/tasks/main.yml
roles/openshift_sro/tasks/main.yml
roles/openshift_sro/tasks/uninstall_sro.yml

Fix default

---

OWNERS

Add Kevin as approver of the project

---

build/root/usr/local/bin/run

apply entitlement manifests when running on CI image

---

ansible.cfg
build/Dockerfile
build/root/usr/local/bin/run
callback_plugins/human_log.py
toolbox/_common.sh

Ansible logs are hard to read with stderr/stdout lines duplicated and everything mangled in JSON.
This patch adds a Python output callback to print more readable information while keeping the gist of it.

Improve logs readability

---

roles/openshift_node/tasks/create_machine.yml

roles/openshift_node/tasks/create_machine.yml: Wait for the GPU machine to be provisioned: fix retry count

---

build/root/usr/local/bin/run
roles/build_ci_image/files/execution_pod.yml
roles/nv_gpu/tasks/ci_checks.yml
roles/nv_gpu/tasks/install_nv.yml
roles/nv_gpu/tasks/main.yml

* 0e41ed2 - roles/nv_gpu/tasks/install_nv.yml: Save the GPU Operator PackageManifests: save YAML instead resource description
* 01533cf - roles/nv_gpu/tasks/main.yml: capture Operator Pod image in extra_logs_dir

Various CI updates

---

.github/workflows/sync-release-branches.yml

last try, I don't think it will work but I would like to understand what's the top of each branch

.github/workflows/sync-release-branches.yml: pull with --ff-only and show current branch commit

---

playbooks/build-psap-ci.yml
roles/build_ci_image/tasks/build.yml
roles/nv_gpu/tasks/ci_checks.yml
roles/nv_gpu/tasks/uninstall_nfd.yml
roles/nv_gpu_install_from_commit/files/helm_deploy_operator.sh
roles/nv_gpu_install_from_commit/tasks/build.yml
roles/nv_gpu_install_from_commit/tasks/cleanup.yml
roles/nv_gpu_install_from_commit/tasks/deploy.yml

* 99213e1 - playbooks/build-psap-ci.yml: remove unused kubeconfig variable definition
* 824fe23 - Use 'oc delete --ignore-not-found=true' instead of 'ignore_errors: true'
* 9cc38cc - roles/nv_gpu/tasks/ci_checks.yml: add 'until' condition to actually retry 5 times

Fixing various details

---

roles/nv_gpu/tasks/install_nv.yml

roles/nv_gpu/tasks/install_nv.yml: Find the GPU Operator OperatorHub InstallPlan: extend delay to 75min

---

README.md
roles/nv_gpu/tasks/main.yml
roles/nv_gpu/tasks/test_nfd.yml
roles/nv_gpu/vars/main.yml
toolbox/gpu-operator/diagnose.sh
toolbox/nfd/has_nfd.sh

New script to diagnose GPU Operator issues on a cluster.

toolbox: gpu-operator/diagnose.sh: new script

---

roles/check_deps/tasks/main.yml
roles/entitlement/files/test_pod.yml
roles/entitlement/meta/main.yml

* 4df20b4 - roles/entitlement/files/test_pod.yml: test the right rhsm file
---
* 04cbc07 - roles/check_deps/tasks/main.yml: store ocp and git version in artifacts
---
* ccf8fbe - roles/entitlement/meta/main.yml: add dependencies to check_deps
---

Various improvements

---

roles/gpu_operator_undeploy_from_operatorhub/tasks/main.yml
toolbox/gpu-operator/cleanup_resources.sh

* 87aaadb - toolbox: gpu-operator/cleanup_resources.sh: correctly call undeploy_from_helm.sh
---
* 19fddca - gpu_operator_undeploy_from_operatorhub: also delete ServiceAccount/gpu-operator
---
* 980bdfa - gpu_operator_cleanup_resources: remove empty role

Various cleanups

---

roles/gpu_operator_deploy_from_operatorhub/tasks/main.yml
roles/nfd_deploy/tasks/main.yml

nfd_deploy: make sure we search only for the NFD ClusterServiceVersion

---

build/Dockerfile
build/root/usr/local/bin/run
build/root/var/lib/ci-artifacts/entrypoints.d/cluster_run_libs.sh
build/root/var/lib/ci-artifacts/entrypoints.d/gpu_operator_run_libs.sh
build/root/var/lib/ci-artifacts/entrypoints.d/sro_run_libs.sh
toolbox/entitlement/entitle.sh
toolbox/gpu-operator/must-gather.sh

This PR modifies the `Dockerfile` & `run` files to move the fetching of dependencies inside the image.
Fixes https://github.com/openshift-psap/ci-artifacts/issues/133

Update Dockerfile to fetch dependencies

---

build/root/usr/local/bin/entitle.sh

This PR updates the location of PSAP secret files, to deploy from the entitlement from PEM key, and deploy the CA PEM file required to access RHEL 8.4-beta repo mirror.

build/root/usr/local/bin/entitle.sh: update to use the new CI vault secrets

---

roles/nfd_operator_deploy_custom_commit/files/operator_image_builder_script.yml

This Patch moves from a fixed sed edit to a hard one replacing the entire line, that one sed won't fail when ever the target string is updated

Fix NFD image URL replacement

---

subprojects/entitled-mirror/README.md
subprojects/entitled-mirror/auth/.gitignore
subprojects/entitled-mirror/auth/README.md
subprojects/entitled-mirror/auth/all.sh
subprojects/entitled-mirror/auth/ca/csr.cnf
subprojects/entitled-mirror/auth/ca/gen_ca.sh
subprojects/entitled-mirror/auth/ca/sign.sh
subprojects/entitled-mirror/auth/client/csr.cnf
subprojects/entitled-mirror/auth/client/gen_client.sh
subprojects/entitled-mirror/auth/delete.sh
subprojects/entitled-mirror/config.env
subprojects/entitled-mirror/containers/build.sh
subprojects/entitled-mirror/containers/serve/Containerfile.serve
subprojects/entitled-mirror/containers/serve/nginx.conf
subprojects/entitled-mirror/containers/sync/Containerfile.sync
subprojects/entitled-mirror/containers/sync/sync_commands.sh
subprojects/entitled-mirror/containers/upload.sh
subprojects/entitled-mirror/cycle.sh
subprojects/entitled-mirror/delete.sh
subprojects/entitled-mirror/delete_pvc.sh
subprojects/entitled-mirror/deploy.sh
subprojects/entitled-mirror/deploy_acme.sh
subprojects/entitled-mirror/openshift/template.yaml
subprojects/entitled-mirror/yum.repo.d/rhods_mirror.repo

See added subprojects/entitled-mirror/README.md for more information

Scripts for deploying an entitled mirror

---

README.rst
docs/toolbox/local-ci.rst

Some missing notes on the docs :)

Update docs after python re-write

---

CHANGELOG.rst
docs/toolbox/gpu_operator.rst
roles/gpu_operator_deploy_from_operatorhub/defaults/main/config.yml
roles/gpu_operator_deploy_from_operatorhub/templates/020_operator_sub.yml.j2
toolbox/gpu-operator/deploy_from_operatorhub.sh

Backport of https://github.com/openshift-psap/ci-artifacts/pull/219/files

[stable-v0.1] toolbox: gpu-operator/deploy_from_operatorhub.sh: add --install-plan=Automatic|Manual flag

---

build/root/usr/local/bin/ci_entrypoint_gpu-operator.sh
build/root/usr/local/bin/ci_entrypoint_sro.sh
roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml

* 755ce46 - CI: undeploy entitlement at the end of the testing
---
* 35e61d5 - gpu_operator_deploy_from_operatorhub: capture the catalog-operator logs when the packagemanifest cannot be found
---

CI: undeploy entitlement at the end of the testing

---

.github/workflows/revert-testing.yml

- `exit` if revert not required :|
- and add a `[TEST TMP]` commit to validate that the action works as expected
- and add `origin master` to `git push` to specify where to push
- and make `git amend` `--quiet`

.github/workflows/revert-testing.yml: exit if revert not required

---

playbooks/benchmarking_deploy_coco_dataset.yml
playbooks/benchmarking_run_nvidiadl_ssd.yml
roles/benchmarking_deploy_coco_dataset/defaults/main/config.yml
roles/benchmarking_deploy_coco_dataset/files/entrypoint.sh
roles/benchmarking_deploy_coco_dataset/meta/main.yml
roles/benchmarking_deploy_coco_dataset/tasks/main.yml
roles/benchmarking_deploy_coco_dataset/templates/pod.yml.j2
roles/benchmarking_deploy_coco_dataset/templates/pvc.yml.j2
roles/benchmarking_deploy_coco_dataset/vars/main/resources.yml
roles/benchmarking_run_nvidiadl_ssd/defaults/main/config.yml
roles/benchmarking_run_nvidiadl_ssd/files/entrypoint.sh
roles/benchmarking_run_nvidiadl_ssd/meta/main.yml
roles/benchmarking_run_nvidiadl_ssd/tasks/main.yml
roles/benchmarking_run_nvidiadl_ssd/templates/nvidiadl-ssd-pod.yml.j2
roles/benchmarking_run_nvidiadl_ssd/vars/main/resources.yml
run_toolbox.py
testing/custom/run_cocodataset_nvidiadl_ssd.sh
toolbox/benchmarking.py

Follow up of #215 (Pam's work) and https://github.com/openshift-psap/ci-artifacts/pull/222 (Coco dataset download example)

ML benchmark playbooks

---

roles/gpu_operator_bundle_from_commit/files/operator_bundle_image_builder_script.yml

Small cleanup of operator_bundle_image_builder_script.yml

gpu_operator_bundle_from_commit: cleanup of operator_bundle_image_builder_script.yml

---

testing/recipes/run_cocodataset_nvidiadl_ssd.sh
testing/run

This part of the modification missed the flight with https://github.com/openshift-psap/ci-artifacts/pull/261

Move testing/nightly to testing/prow

---

roles/gpu_operator_wait_deployment/tasks/metrics.yml

gpu_operator_wait_deployment: fix DCGM metrics destination file

---

testing/prow/gpu-operator.sh

testing: prow/gpu-operator: use JOB_NAME to distinguish test bundles and images

---

roles/gpu_operator_deploy_from_operatorhub/tasks/deploy_from_catalog.yml
roles/gpu_operator_deploy_from_operatorhub/templates/010_operator_group.yml.j2
roles/gpu_operator_deploy_from_operatorhub/vars/main/resources.yml
testing/prow/gpu-operator.sh
testing/run
toolbox/gpu_operator.py

and refresh a bit the role and entrypoint.

gpu_operator_deploy_from_operatorhub: update to support v1.9 deployment

---

testing/prow/gpu-operator.sh

This got broken with the must-gather capture.

testing: prow/gpu-operator.sh: properly capture the GPU Operator version

---

testing/prow/nfd-operator.sh

NFD add test_branch function

---

.github/workflows/sync-release-branches.yml

.github/workflows/sync-release-branches.yml: add 4.10 branch synchronization

---

subprojects/wdm/wdm.py
testing/prow/entitle.sh
testing/prow/gpu-operator.sh
testing/recipes/run_cocodataset_nvidiadl_ssd.sh
testing/wdm/gpu-operator.yml
toolbox/wdm

* `[wdm] add POC script for WDM dependency resolution`
---
* `testing: prow: use WDM to resolve entitlement and GPU Operator dependencies`
---
* `testing: recipes/run_cocodataset_nvidiadl_ssd.sh: use WDM to resolve the GPU Operator dependency`
---

[wdm] add POC script for WDM dependency resolution and use it in our test scripts

---

subprojects/wdm/wdm.py

* `[wdm] Delete ansible temp file after execution`
---
* `[wdm] remove hardcoded path from ansible-playbook`
---
* `[wdm] flush stdout/err before calling subprocess.run`
---

[wdm] Improve

---

roles/benchmarking_deploy_coco_dataset/files/entrypoint.sh

benchmarking_deploy_coco_dataset: download image_info_test2017.zip and use sha256

---

subprojects/wdm/wdm.py
testing/wdm/gpu-operator.yml

/cc @Maxusmusti I cherry-picked the last commit from your branch

[wdm] Various fixes

---

subprojects/wdm/wdm.py
testing/mpi/.gitignore
testing/mpi/001_imagestream.yaml
testing/mpi/002_base_image.buildconfig.yaml
testing/mpi/003_base_image.python.buildconfig.yaml
testing/mpi/004_osu-mpi.buildconfig.yaml
testing/mpi/dependencies.yaml
testing/mpi/rootless/mpijob-osu.yaml
testing/mpi/rootless/mpijob.yaml
testing/mpi/rootless/run.sh
testing/mpi/run.sh
testing/mpi/sshdless/mpijob.yaml
testing/mpi/sshdless/run.sh
testing/mpi/sshdless/sshd_server.py
testing/mpi/sshless/connect.sh
testing/mpi/sshless/mpijob.yaml
testing/mpi/sshless/run.sh
testing/mpi/sshless/server.py
testing/mpi/wait_and_collect.sh

testing: mpi: start working on rootless MPI testing

---

subprojects/wdm/wdm.py

[wdm] Allow dependencies to have no install tasks

---

subprojects/cloud-watch/ec2.py

Starting this project to help over-watching our AWS resource usage, and avoid  wasting money with dangling resources
Example of output of ``:
```
kpouget-20220318-kr2fw
======================
Age: 0 days
Region: eu-central-1
i-.... m5.xlarge running kpouget-20220318-...-master-0
i-... g4dn.xlarge running kpouget-20220318-...-worker-eu-central-1a--g4dn-xlarge-...
i-... g4dn.xlarge running kpouget-20220318-...-worker-eu-central-1a--g4dn-xlarge-...
```

[cloud-watch] ec2.py: new file

---

OWNERS

I am no longer capable of being an `approver`, moving my role to just `reviewer` 

Update project ownership

---

toolbox/_common.py

toolbox/_common.py: do not print a stack trace on Ctrl-C

---

subprojects/sno-snapshot/src/common.py
subprojects/sno-snapshot/src/rollback.py
subprojects/sno-snapshot/src/snapshot.py

Without this, it only worked when the cluster was in the default region.
/cc @kpouget

[sno-snapshot] Lookup the region from the cluster machines

---

subprojects/deploy-osd-rhods/env.kevin

(no secret leaked)
/cc @kpouget

[deploy-osd-rhods] remove env.kevin

---

testing/ods/osd_cluster.sh

testing: ods/osd_cluster.sh: test $SHARED_DIR multi-stage shared directory

---

roles/cluster_deploy_osd/meta/main.yml
roles/ocm_deploy_addon/meta/main.yml
roles/utils_build_push_image/meta/main.yml

Add missing dependencies to 'check_deps'

---

build/Dockerfile

Dockerfile: make more silent

---

roles/cluster_deploy_minio_s3_server/files/deploy_minio.yaml
roles/rhods_test_jupyterlab/files/entrypoint.sh
roles/rhods_test_jupyterlab/tasks/main.yml
roles/rhods_test_jupyterlab/templates/rhods-ci.yaml

rhods_test_jupyterlab: rework artifact extraction

---

testing/test-pr.sh

testing: test-pr: removing trailing \r in the PR body

---

roles/cluster_destroy_ocp/defaults/main/config.yml
roles/cluster_destroy_ocp/meta/main.yml
roles/cluster_destroy_ocp/tasks/main.yml
roles/cluster_destroy_ocp/templates/metadata.json.j2
subprojects/deploy-cluster/config_install.mk
toolbox/cluster.py

* `[deploy-cluster] make wget quiet`
---
* `cluster_destroy_ocp: make it work`
---

Update deploy-cluster and cluster_destroy_ocp

---

roles/nfd_operator_deploy_custom_commit/files/operator_helper_image_builder.yml
roles/utils_build_push_image/templates/helper_buildconfig.yml.j2

Cherry picked from https://github.com/rh-ecosystem-edge/ci-artifacts/pull/35/commits
/cc @kpouget

NFD: Using fedora:35 for helper_image_builder.

---

build/Dockerfile
roles/cluster_create_osd/tasks/main.yml
testing/gather-extra.sh
testing/ods/clusters.sh
testing/ods/common.sh
testing/ods/jh-at-scale.sh
testing/ods/osd_cluster.sh
testing/ods/process_ctrl.sh

RHODS: Launch OCP as part of the test

---

roles/cluster_deploy_minio_s3_server/files/deploy_minio.yaml
roles/rhods_test_jupyterlab/files/entrypoint.sh
roles/rhods_test_jupyterlab/tasks/main.yml
testing/ods/jh-at-scale.sh

RHODS: minor updates

---

testing/ods/clusters.sh

... and shunt the cluster creation until openshift/release PR is merged
/cc @kpouget

testing: ods: clusters: parse the create/destroy mode

---

testing/ods/clusters.sh
testing/ods/common.sh
testing/ods/jh-at-scale.sh
testing/ods/ocp_cluster.sh
testing/ods/osd_cluster.sh
testing/ods/process_ctrl.sh
testing/ods/secrets.sample/.awscred
testing/ods/secrets.sample/pull-secret
testing/ods/secrets.sample/ssh-publickey

testing: ods: clusters: support multiple sutest cluster types

---

roles/cluster_create_osd/defaults/main/config.yml
roles/cluster_create_osd/tasks/main.yml
roles/ocm_deploy_addon/tasks/main.yml
testing/ods/common.sh

cluster_create_osd: better wait for OSD to be ready

---

build/Dockerfile

build/Dockerfile: install Python3.9 instead of Python3.6

---

build/Dockerfile

/cc @fcami , if you can help me activate that? it keeps failing :(
or we turn to `centos`

WIP: build/Dockerfile: active Python3.9 as default python3

---

roles/rhods_test_jupyterlab/tasks/main.yml

rhods_test_jupyterlab: Generate MatrixBenchmark files: use only _, not -

---

testing/ods/common.sh

testing: ods: common: ajust ODS_NOTEBOOK_SIZE to match the notebook currently size in use

---

build/Dockerfile
testing/ods/generate_matrix-benchmarking.sh

```
matbench-data-url: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/404/pull-ci-openshift-psap-ci-artifacts-master-ods-jh-on-ocp/1544214836106235904/artifacts/jh-on-ocp/test/artifacts/
```

RHODS: load MatrixBenchmarking to generate execution graphs

---

subprojects/cloud-watch/cleanup-rhods-zombie.py
subprojects/cloud-watch/ec2.py

[cloud-watch] Integrate Route53 hosted zones (for information)

---

OWNERS

OWNERS: add fcami as approver

---

.gitleaks.toml
testing/ods/clusters.sh
testing/ods/common.sh
testing/ods/generate_matrix-benchmarking.sh
testing/ods/ocp_cluster.sh
testing/ods/osd_cluster.sh

RHODS: improve get-cluster's job

---

testing/ods/common.sh
testing/ods/jh-at-scale.sh

testing: ods: jh-at-scale: introduce ODS_EXCLUDE_TAGS variable

---

testing/ods/jh-at-scale.sh

Regression was introduced in https://github.com/openshift-psap/ci-artifacts/pull/433.
/cc @kpouget

testing: ods: jh-at-scale: fix call to 'cluster undeploy_ldap'

---

subprojects/matrix-benchmarking-workloads/rhods-ci/data/ci-artifacts.plots
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/__init__.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/advanced_timeline.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/error_report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/mapping.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/simple_timeline.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/timeline_data.py
subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/generate_matrix-benchmarking.sh

```
matbench-data-url: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/420/pull-ci-openshift-psap-ci-artifacts-master-ods-jh-on-ocp/1548174089028374528/artifacts/jh-on-ocp/test/artifacts/
```

testing: ods: generate_matrix-benchmarking: fix to use the local matbench workload directory

---

subprojects/matrix-benchmarking-workloads/rhods-ci/data/ci-artifacts.plots
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/__init__.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/prom.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/prom_report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/generate_matrix-benchmarking.sh

/cc @kpouget 
```
matbench-data-url: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/420/pull-ci-openshift-psap-ci-artifacts-master-ods-jh-on-osd/1549628325947772928/artifacts/jh-on-osd/test/artifacts/
```

[matrix-benchmarking-workloads/rhods-ci] Improve Prometheus parsing and visualization

---

.gitmodules
build/Dockerfile
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/error_report.py
testing/ods/generate_matrix-benchmarking.sh

/cc @kpouget 
```
matbench-data-url: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/460/pull-ci-openshift-psap-ci-artifacts-master-ods-get-cluster/1551835589391683584/artifacts/get-cluster/test/artifacts/
```

RHODS: Add MatrixBenchmarking as a subproject

---

subprojects/cloud-watch/cleanup-rhods-zombie.py

* `[cloud-watch] Include resource without tags in the delete list`
... if their name matches the CI prefix
---
* `[cloud-watch] Call wait_database_deletions at the right level`
---
/cc @kpouget

[cloud-watch] Fix bugs

---

subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/common.sh
testing/ods/generate_matrix-benchmarking.sh
testing/ods/jh-at-scale.sh

List of changes to prepare running on non-CI clusters
```
test-path: ods jh-at-scale install_rhods
test-path: ods jh-at-scale install_ldap
test-path: ods jh-at-scale prepare_driver_cluster
test-path: ods jh-at-scale run_jupyterlab_test
test-path: ods jh-at-scale generate_plots
```

RHODS: Prepare for external clusters

---

testing/ods/cleanup/zombies.sh
testing/ods/ocp_cluster.sh

Without this patch, cluster destruction and cleanup are broken
/cc @kpouget

testing: ods: finish exposing AWS_PROFILE

---

testing/ods/cleanup/velero-buckets.sh
testing/ods/cleanup/zombies.sh

testing: ods: cleanup: fix AWS configuration

---

build/Dockerfile

build/Dockerfile: simplify to reduce the build-time memory footprint

---

build/Dockerfile
testing/ods/generate_matrix-benchmarking.sh
testing/ods/run_customer_notebook_ux_e2e_scale_test.sh

RHODS: Generate a report index

---

testing/pr_args.sh

testing: pr_args: remove hardcoded values

---

roles/cluster_preload_image/tasks/main.yml
roles/rhods_capture_state/tasks/capture_namespace.yml
roles/rhods_capture_state/tasks/main.yml
roles/rhods_notebook_ux_e2e_scale_test/files/ods-ci/notebook_ux_e2e_test.robot
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts_sutest.yml
roles/rhods_notebook_ux_e2e_scale_test/tasks/main.yml
roles/rhods_wait_ods/tasks/main.yml
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/prom.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/prom_report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/common.sh
testing/ods/generate_matrix-benchmarking.sh
testing/ods/notebook_ux_e2e_scale_test.sh

This PR refactors the RHODS testing and plotting code to work with Kubeflow Notebook Controller (KFNBC) integrated in RHODS 1.15 and 1.16.

RHODS: switch to KFNBC (RHODS 1.16)

---

testing/ods/common.sh
testing/ods/notebook_ux_e2e_scale_test.sh

testing: ods: notebook_ux_e2e_scale_test: no need to explicitely enable KFNBC anymore

---

build/Dockerfile

This reverts commit e83b8f30be8c85b704789ab5fd45eb301962d4d4.

Revert "build/Dockerfile: download custom copy of openshift-client-linux.tar.gz"

---

roles/rhods_capture_state/tasks/capture_namespace.yml
roles/rhods_capture_state/tasks/main.yml
roles/rhods_cleanup_notebooks/defaults/main/config.yml
roles/rhods_cleanup_notebooks/meta/main.yml
roles/rhods_cleanup_notebooks/tasks/main.yml
roles/rhods_deploy_ods/tasks/main.yml
roles/rhods_notebook_ux_e2e_scale_test/files/entrypoint.sh
roles/rhods_notebook_ux_e2e_scale_test/files/ods-ci/notebook_ux_e2e_test.robot
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts_sutest.yml
roles/rhods_notebook_ux_e2e_scale_test/tasks/main.yml
roles/rhods_notebook_ux_e2e_scale_test/templates/ods-ci_job.yaml
subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/common.sh
testing/ods/notebook_ux_e2e_scale_test.sh
testing/ods/run_private_notebook_ux_e2e_scale_test.sh
testing/ods/sizing/machines
testing/pr_args.sh
toolbox/cluster.py
toolbox/rhods.py
toolbox/utils.py

/var CUSTOMIZE_RHODS_DASHBOARD_FORCED_IMAGE=quay.io/opendatahub/odh-dashboard:main

RHODS: test next version

---

roles/rhods_notebook_ux_e2e_scale_test/files/entrypoint.sh
roles/rhods_notebook_ux_e2e_scale_test/files/s3-artifacts-exporter.sh
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts_driver.yml
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts_sutest.yml
roles/rhods_notebook_ux_e2e_scale_test/tasks/main.yml
roles/rhods_notebook_ux_e2e_scale_test/templates/ods-ci_job.yaml

/cc @kpouget 
in preparation of the arrival of the API-level testing (https://github.com/openshift-psap/ci-artifacts/pull/496)

rhods_notebook_ux_e2e_scale_test: make more flexible

---

roles/rhods_wait_ods/defaults/main/config.yml
roles/rhods_wait_ods/tasks/main.yml
testing/ods/clusters.sh
testing/ods/common.sh
testing/ods/notebook_ux_e2e_scale_test.sh
testing/ods/ocp_cluster.sh
testing/ods/sizing/sizing

/cc @kpouget 
/var ODS_CATALOG_IMAGE_TAG=1.16.0-hotfix-27165b

RHODS: test the next version

---

subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/status.py

[matrix-benchmarking-workloads/rhods-ci] Plot the distribution of the time to reach JupyterLab

---

roles/rhods_deploy_ods/tasks/main.yml
roles/rhods_notebook_ux_e2e_scale_test/files/ods-ci/notebook_ux_e2e_test.robot
testing/ods/notebook_ux_e2e_scale_test.sh

/var ODS_CATALOG_IMAGE_TAG=v1160-6

RHODS: minor improvements

---

subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/error_report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/mapping.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/notebook_ux_e2e_scale_test.sh

RHODS: improve plotting and reporting

---

roles/cluster_ensure_machineset/defaults/main/config.yml
roles/cluster_ensure_machineset/scripts/reconfigure_machineset.sh
roles/cluster_ensure_machineset/tasks/derive_machineset.yml
roles/cluster_ensure_machineset/tasks/main.yml
roles/cluster_preload_image/defaults/main/config.yml
roles/cluster_preload_image/templates/daemonset.yaml.j2
roles/cluster_set_scale/defaults/main/config.yml
roles/cluster_set_scale/tasks/main.yml
roles/rhods_notebook_api_scale_test/defaults/main/config.yml
roles/rhods_notebook_api_scale_test/templates/api_scale_test_job.yaml
roles/rhods_notebook_ux_e2e_scale_test/defaults/main/config.yml
roles/rhods_notebook_ux_e2e_scale_test/templates/ods-ci_job.yaml
roles/utils_build_push_image/tasks/build_image.yml
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/error_report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/status.py
subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/common.sh
testing/ods/notebook_ux_e2e_scale_test.sh
testing/ods/ocp_cluster.sh
testing/ods/osd_cluster.sh
testing/ods/private_cluster.sh
toolbox/cluster.py
toolbox/rhods.py

/var ODS_CI_NB_USERS=5
/var ODS_CATALOG_IMAGE_TAG=1.17.0-3
/var NOTEBOOK_TEST_RUNS=2

RHODS: Rework cluster scaling and introduce taints&tolerations

---

roles/rhods_notebook_ux_e2e_scale_test/files/entrypoint.sh
roles/rhods_notebook_ux_e2e_scale_test/files/state-signal_barrier.py
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts_sutest.yml
roles/utils_build_push_image/tasks/build_image.yml
roles/utils_build_push_image/tasks/main.yml
testing/ods/notebook_ux_e2e_scale_test.sh

/var ODS_CATALOG_IMAGE_TAG=1.17.0-5
/var NOTEBOOK_TEST_RUNS=2

RHODS: test 1.17

---

roles/rhods_notebook_ux_e2e_scale_test/files/entrypoint.sh
subprojects/deploy-cluster/cluster_single-master.mk
subprojects/deploy-cluster/cluster_sno.mk
subprojects/matrix-benchmarking-workloads/rhods-ci/data/ci-artifacts.plots
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/mapping.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/prom.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/spawntime.py
subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/notebook_ux_e2e_scale_test.sh
testing/ods/sizing/sizing

RHODS: improve the visualization

---

roles/cluster_deploy_operator/tasks/main.yml
roles/cluster_deploy_operator/templates/operator_group.yml.j2
roles/cluster_deploy_operator/templates/subscription.yml.j2

cluster_deploy_operator: fix issues when deploying in all the namespaces

---

testing/pr_args.sh

Update following master->main transition

---

roles/cluster_deploy_operator/tasks/main.yml
roles/cluster_deploy_operator/templates/operator_group.yml.j2
roles/rhods_cleanup_notebooks/tasks/main.yml
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/completion.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/error_report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/notebook_performance.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/prom.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/report.py
subprojects/matrix-benchmarking-workloads/rhods-ci/plotting/status.py
subprojects/matrix-benchmarking-workloads/rhods-ci/store.py
testing/ods/common.sh
testing/ods/generate_matrix-benchmarking.sh
testing/ods/notebook_ux_e2e_scale_test.sh
testing/run

testing: ods: run the last test with only 1 user

---

roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts.yml
testing/ods/clusters.sh
testing/ods/private_cluster.sh

/var ODS_CATALOG_IMAGE_TAG=1.17.0-5
/var ODS_CI_NB_USERS=50
/var ODS_SLEEP_FACTOR=0
/var NOTEBOOK_TEST_RUNS=1
/var LAST_NOTEBOOK_TEST_RUN_IS_SINGLE=0

RHODS: test with ROSA

---

subprojects/matrix-benchmarking-workloads/rhods-ci/store.py

[matrix-benchmarking-workloads/rhods-ci] store: parse notebook_pods.yaml and tester_pods.yaml manually

---

build/Dockerfile

Update for UBI9

---

roles/cluster_preload_image/templates/daemonset.yaml.j2
testing/ods/clusters.sh
testing/ods/config_clusters.sh
testing/ods/notebook_scale_test.sh
testing/ods/ocp_cluster.sh
testing/ods/osd_cluster.sh
testing/pr_args.sh
toolbox/cluster.py

/var ODS_CATALOG_IMAGE_TAG=1.18.0-6
/var ODS_CI_NB_USERS=100
/var NOTEBOOK_TEST_RUNS=3

RHODS: various updates

---

.github/workflows/check_wip.yml
testing/run
toolbox/repo.py
toolbox/repo_scripts/validate_no_wip.sh
toolbox/repo_scripts/validate_role_files.py
toolbox/repo_scripts/validate_role_vars_used.py

toolbox: validate_no_wip.sh: new Github Action to ensure that their is no WIP commit in the PR

---

toolbox/_common.py
toolbox/benchmarking.py
toolbox/cluster.py
toolbox/entitlement.py
toolbox/gpu_operator.py
toolbox/nfd.py
toolbox/nfd_operator.py
toolbox/nto.py
toolbox/rhods.py
toolbox/utils.py

toolbox: rework the Python code launching Ansible 

---

testing/test-pr.sh

testing: test-pr: use PR_POSITIONAL_ARGS

---

testing/test-pr.sh

testing: test-pr: log an error if $PR_POSITIONAL_ARGS isn't defined

---

subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py
testing/ods/generate_matrix-benchmarking.sh

[matrix-benchmarking-workloads/rhods-notebooks-ux] store: ignore FileNotFoundError errors during the parsing

---

testing/ods/generate_matrix-benchmarking.sh

testing: ods: generate_matrix-benchmarking: allow comments in the plot list file

---

testing/ods/clusters.sh

testing: ods: clusters: correctly create the default KUBECONFIG

---

testing/pr_args.sh
testing/run

testing: use '$REPO_OWNER/$REPO_NAME' to refere to the repository

---

roles/rhods_notebook_ux_e2e_scale_test/files/s3-artifacts-exporter.sh

rhods_notebook_ux_e2e_scale_test: s3-artifacts-exporter: fix screenshot deletion

---

toolbox/repo_scripts/validate_no_wip.sh

toolbox: repo_scripts: validate_no_wip: check for wip flag in the PR title

---

testing/ods/clusters.sh

testing: ods: clusters: fix keep cluster

---

testing/ods/cleanup/zombies.sh

testing: ods: cleanup/zombies.sh: fix following refactoring

---

subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/data/notebook_perf_comparison.yaml

testing: ods: config: run the single notebook test

---

testing/ods/ci_init_configure.sh
testing/ods/cluster_helpers.sh
testing/ods/clusters.sh
testing/ods/config.yaml
testing/ods/notebook_scale_test.sh
testing/ods/ocp_cluster.sh
testing/ods/osd_cluster.sh
testing/ods/secrets.sample/ocm.token
toolbox/cluster.py

/var rhods.catalog.tag=v1190-14

testing: ods: fix OSD cluster creation following the refactoring

---

testing/model-mesh/1-install-mm.sh
testing/model-mesh/modelmesh.yaml

/var matbench.config_file=model_mesh.yaml

Model Mesh: switch to the ODH Operator

---

subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/data/notebooks_scale_tests_comparison.yaml
testing/ods/config.yaml

RHODS 1.19 visu

---

roles/rhods_notebook_ux_e2e_scale_test/files/ods-ci/notebook_dsg_e2e_test.robot
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts.yml
roles/rhods_notebook_ux_e2e_scale_test/vars/main/resources.yml
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py
testing/ods/config.yaml

RHODS: various updates for 1.19 testing

---

roles/rhods_notebook_ux_e2e_scale_test/files/ods-ci/notebook_dsg_e2e_test.robot
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts.yml
roles/rhods_notebook_ux_e2e_scale_test/vars/main/resources.yml
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py
testing/ods/config.yaml

/var rhods.catalog.tag=v1190-14
/var tests.notebooks.users.count=20
/var tests.notebooks.ods_ci.test_case=notebook_dsg_e2e_test.robot
/var clusters.create.ocp.control_plane.type=m6i.xlarge
/var clusters.create.ocp.compute.type=m6i.2xlarge

WIP: RHODS: test 1.19

---

roles/rhods_notebook_ux_e2e_scale_test/files/ods-ci/notebook_dsg_e2e_test.robot
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/data/notebooks_scale_tests_comparison.yaml
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/error_report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/multi_notebook_spawn_time.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/perf_report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/prom_report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/status.py
testing/ods/notebook_scale_test.sh

/cc @kpouget 
/var rhods.catalog.tag=v1190-14
/var tests.notebooks.users.count=5
/var tests.notebooks.ods_ci.test_case=notebook_dsg_e2e_test.robot
/var clusters.create.ocp.control_plane.type=m6i.xlarge
/var clusters.create.ocp.compute.type=m6i.2xlarge

RHODS 1.19 testing

---

roles/rhods_benchmark_notebook_performance/defaults/main/config.yml
roles/rhods_benchmark_notebook_performance/meta/main.yml
roles/rhods_benchmark_notebook_performance/tasks/artifacts_sutest.yml
roles/rhods_benchmark_notebook_performance/tasks/artifacts_sutest_project.yml
roles/rhods_benchmark_notebook_performance/tasks/main.yml
roles/rhods_benchmark_notebook_performance/templates/notebook.yaml
roles/rhods_benchmark_notebook_performance/vars/main/resources.yml
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts_sutest.yml
roles/rhods_notebook_ux_e2e_scale_test/tasks/artifacts_sutest_project.yml
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/data/single_notebook_perf.yaml
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/notebook_performance.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py
testing/ods/command_args.yaml
testing/ods/config.yaml
testing/ods/notebook_scale_test.sh
testing/process_ctrl.sh
toolbox/from_config.py
toolbox/rhods.py

/var tests.notebooks.flavor_to_run=notebook-performance
/var tests.notebooks.notebook_performance.use_rhods=false
/var matbench.config_file=single_notebook_perf.yaml

RHODS: simplify single notebook benchmarking

---

roles/cluster_deploy_minio_s3_server/tasks/main.yml
roles/rhods_notebook_ods_ci_scale_test/files/ods-ci/notebook_dsg_test.robot
roles/rhods_notebook_ods_ci_scale_test/files/ods-ci/notebook_jupyter_test.robot
roles/rhods_notebook_ods_ci_scale_test/files/ods-ci/notebook_scale_test_common.resource
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/error_report.py
testing/_logging.sh
testing/ods/brew.registry.redhat.io/setup.sh
testing/ods/cluster_helpers.sh
testing/ods/config.yaml
testing/ods/configure_overrides.sh
testing/ods/configure_set_presets.sh
testing/ods/notebook_scale_test.sh

/var ci_presets.name=jupyter_notebook_scale_test
/var rhods.catalog.tag=v120-11

RHODS: test 1.20

---

roles/rhods_notebook_ods_ci_scale_test/files/ods-ci/notebook_dsg_test.robot
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/mapping.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/prom.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/spawntime.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py
testing/ods/clusters.sh
testing/ods/config.yaml

/var ci_presets.name=notebook_scale_test
/var rhods.catalog.tag=v120-11

Testing RHODS 1.20

---

toolbox/nfd_operator.py

Fix the entrypoint of `nfd_operator deploy_from_operatorhub` following the last refactoring
/cc @Maxusmusti  FYI

toolbox: nfd_operator: fix deploy_from_operatorhub

---

toolbox/nfd_operator.py

toolbox: nfd_operator: finish deploy_from_operatorhub refactoring

---

subprojects/oauth-proxy_scale_test/.gitignore
subprojects/oauth-proxy_scale_test/benchmark.yaml
subprojects/oauth-proxy_scale_test/exec/run_test.py
subprojects/oauth-proxy_scale_test/plotting/__init__.py
subprojects/oauth-proxy_scale_test/setup/launch.sh
subprojects/oauth-proxy_scale_test/setup/oauth-proxy.yaml
subprojects/oauth-proxy_scale_test/store.py
subprojects/oauth-proxy_scale_test/store_prom.py

[oauth-proxy_scale_test] New subproject

---

testing/notebooks/config.yaml
testing/pipelines/config.yaml

testing: notebooks: config: add TicketId for the gating and large_scale tests

---

subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/horreum_lts_store.py
testing/notebooks/generate_matrix-benchmarking.sh

@kdvalin, I did some modifications of your code
Some of the changes are personal taste (justified by the consistency with the rest of the repo), 
simpler constructs, naming consistency, and better tolerance to incomplete data results
I'll add comments in the code to explain
Ignore the files not related to your work, it's a rebase on top of #691

RHODS: improve the LTS code consistency

---

subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/horreum_lts_store.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/completion.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/error_report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/gating_report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/launch_time.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/mapping.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/multi_notebook_spawn_time.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/notebook_performance.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/perf_report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/prom.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/report.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/spawntime.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/status.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/plotting/utils.py
subprojects/matrix-benchmarking-workloads/rhods-notebooks-ux/store.py

This PR aims to integrate Horreum results with `matbench visualize --workload=rhods-notebooks-ux ...` and allow for it to be displayed alongside local results for gating reports and the performance report.

Work on local Horreum plotting

---

testing/utils/openshift_clusters/ocp_cluster.sh

This reverts commit aa0284ca5d61f457955b7c61a8dc9ccedcca829b.

Revert "testing: ods: ocp_cluster: save logs in a dedicated directory"

---

testing/notebooks/config.yaml

Added tests to use for 200 users targeting the icelake cluster.  Will be updating this with information from Jenkins as it becomes available.

Icelake Cluster 200 user test

---

testing/load-aware/scale_test.py

Start OCP pipeline install when running the load-aware scale test. Might need to add more to prepare and cleanup later for load-aware since this is difficult to test outside the CI environment.

load-aware: Install OCP pipelines during the cluster preparation

---

testing/notebooks/prepare_sutest.sh

it swallows the failing of the $() command ...

testing: notebooks: prepare_sutest: remove 'local' variable

---

testing/codeflare/images/Containerfile.codeflare_sdk
testing/codeflare/sdk_user/sample/sample.py

as a workaround for https://github.com/project-codeflare/codeflare-sdk/issues/250

testing: codeflare: sdk_user/sample/sample: retry 'cluster.wait_ready' multiple times
